/-
Arbitrary presentation complexes and the genuine Hausdorff CW realization of every group.
Mathematical source: Allen Hatcher, Algebraic Topology, Corollary 1.28.
Authors: Arthur Freitas Ramos, David Barros Hulak,
Ruy Jose Guerra Barretto de Queiroz.
First-party source: Apache-2.0. Reused source notices are retained below.
Generated by scripts/generate_standalone.py; edit the modular sources instead.
-/
/-
Apache-2.0 license for first-party and Apache-licensed reused sources.

                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.

      "License" shall mean the terms and conditions for use, reproduction,
      and distribution as defined by Sections 1 through 9 of this document.

      "Licensor" shall mean the copyright owner or entity authorized by
      the copyright owner that is granting the License.

      "Legal Entity" shall mean the union of the acting entity and all
      other entities that control, are controlled by, or are under common
      control with that entity. For the purposes of this definition,
      "control" means (i) the power, direct or indirect, to cause the
      direction or management of such entity, whether by contract or
      otherwise, or (ii) ownership of fifty percent (50%) or more of the
      outstanding shares, or (iii) beneficial ownership of such entity.

      "You" (or "Your") shall mean an individual or Legal Entity
      exercising permissions granted by this License.

      "Source" form shall mean the preferred form for making modifications,
      including but not limited to software source code, documentation
      source, and configuration files.

      "Object" form shall mean any form resulting from mechanical
      transformation or translation of a Source form, including but
      not limited to compiled object code, generated documentation,
      and conversions to other media types.

      "Work" shall mean the work of authorship, whether in Source or
      Object form, made available under the License, as indicated by a
      copyright notice that is included in or attached to the work
      (an example is provided in the Appendix below).

      "Derivative Works" shall mean any work, whether in Source or Object
      form, that is based on (or derived from) the Work and for which the
      editorial revisions, annotations, elaborations, or other modifications
      represent, as a whole, an original work of authorship. For the purposes
      of this License, Derivative Works shall not include works that remain
      separable from, or merely link (or bind by name) to the interfaces of,
      the Work and Derivative Works thereof.

      "Contribution" shall mean any work of authorship, including
      the original version of the Work and any modifications or additions
      to that Work or Derivative Works thereof, that is intentionally
      submitted to Licensor for inclusion in the Work by the copyright owner
      or by an individual or Legal Entity authorized to submit on behalf of
      the copyright owner. For the purposes of this definition, "submitted"
      means any form of electronic, verbal, or written communication sent
      to the Licensor or its representatives, including but not limited to
      communication on electronic mailing lists, source code control systems,
      and issue tracking systems that are managed by, or on behalf of, the
      Licensor for the purpose of discussing and improving the Work, but
      excluding communication that is conspicuously marked or otherwise
      designated in writing by the copyright owner as "Not a Contribution."

      "Contributor" shall mean Licensor and any individual or Legal Entity
      on behalf of whom a Contribution has been received by Licensor and
      subsequently incorporated within the Work.

   2. Grant of Copyright License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      copyright license to reproduce, prepare Derivative Works of,
      publicly display, publicly perform, sublicense, and distribute the
      Work and such Derivative Works in Source or Object form.

   3. Grant of Patent License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      (except as stated in this section) patent license to make, have made,
      use, offer to sell, sell, import, and otherwise transfer the Work,
      where such license applies only to those patent claims licensable
      by such Contributor that are necessarily infringed by their
      Contribution(s) alone or by combination of their Contribution(s)
      with the Work to which such Contribution(s) was submitted. If You
      institute patent litigation against any entity (including a
      cross-claim or counterclaim in a lawsuit) alleging that the Work
      or a Contribution incorporated within the Work constitutes direct
      or contributory patent infringement, then any patent licenses
      granted to You under this License for that Work shall terminate
      as of the date such litigation is filed.

   4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and

      (b) You must cause any modified files to carry prominent notices
          stating that You changed the files; and

      (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work,
          excluding those notices that do not pertain to any part of
          the Derivative Works; and

      (d) If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.

      You may add Your own copyright statement to Your modifications and
      may provide additional or different license terms and conditions
      for use, reproduction, or distribution of Your modifications, or
      for any such Derivative Works as a whole, provided Your use,
      reproduction, and distribution of the Work otherwise complies with
      the conditions stated in this License.

   5. Submission of Contributions. Unless You explicitly state otherwise,
      any Contribution intentionally submitted for inclusion in the Work
      by You to the Licensor shall be under the terms and conditions of
      this License, without any additional terms or conditions.
      Notwithstanding the above, nothing herein shall supersede or modify
      the terms of any separate license agreement you may have executed
      with Licensor regarding such Contributions.

   6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work and reproducing the content of the NOTICE file.

   7. Disclaimer of Warranty. Unless required by applicable law or
      agreed to in writing, Licensor provides the Work (and each
      Contributor provides its Contributions) on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
      implied, including, without limitation, any warranties or conditions
      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
      PARTICULAR PURPOSE. You are solely responsible for determining the
      appropriateness of using or redistributing the Work and assume any
      risks associated with Your exercise of permissions under this License.

   8. Limitation of Liability. In no event and under no legal theory,
      whether in tort (including negligence), contract, or otherwise,
      unless required by applicable law (such as deliberate and grossly
      negligent acts) or agreed to in writing, shall any Contributor be
      liable to You for damages, including any direct, indirect, special,
      incidental, or consequential damages of any character arising as a
      result of this License or out of the use or inability to use the
      Work (including but not limited to damages for loss of goodwill,
      work stoppage, computer failure or malfunction, or any and all
      other commercial damages or losses), even if such Contributor
      has been advised of the possibility of such damages.

   9. Accepting Warranty or Additional Liability. While redistributing
      the Work or Derivative Works thereof, You may choose to offer,
      and charge a fee for, acceptance of support, warranty, indemnity,
      or other liability obligations and/or rights consistent with this
      License. However, in accepting such obligations, You may act only
      on Your own behalf and on Your sole responsibility, not on behalf
      of any other Contributor, and only if You agree to indemnify,
      defend, and hold each Contributor harmless for any liability
      incurred by, or claims asserted against, such Contributor by reason
      of your accepting any such warranty or additional liability.

   END OF TERMS AND CONDITIONS

   APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

   Copyright 2026 Arthur Freitas Ramos

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

-/
/-
Vendored directed-topology helpers retain this MIT notice.
Copyright 2023 Dominique Lawson

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-/
module

public import Mathlib.AlgebraicTopology.FundamentalGroupoid.FundamentalGroup
public import Mathlib.AlgebraicTopology.FundamentalGroupoid.InducedMaps
public import Mathlib.Topology.Connected.PathConnected
public import Mathlib.Topology.Constructions
public import Mathlib.Topology.Order
public import Mathlib.CategoryTheory.Groupoid.FreeGroupoid
public import Mathlib.CategoryTheory.Endomorphism
public import Mathlib.Combinatorics.Quiver.Arborescence
public import Mathlib.GroupTheory.FreeGroup.NielsenSchreier
public import Mathlib.CategoryTheory.SingleObj
public import Mathlib.Topology.Covering.Basic
public import Mathlib.Topology.Homotopy.Lifting
public import Mathlib.GroupTheory.FreeGroup.Reduce
public import Mathlib.Combinatorics.Quiver.Covering
public import Mathlib.AlgebraicTopology.FundamentalGroupoid.SimplyConnected
public import Mathlib.Topology.Homeomorph.Lemmas
public import Mathlib.Topology.CWComplex.Classical.Basic
public import Mathlib.Topology.UnitInterval
public import Mathlib.Analysis.Convex.GaugeRescale
public import Mathlib.Analysis.Complex.Basic
public import Mathlib.Topology.Covering.AddCircle
public import Mathlib.Topology.Instances.ZMultiples
public import Mathlib.Analysis.Convex.Contractible
public import Mathlib.Analysis.SpecialFunctions.Complex.Circle
public import Mathlib.Analysis.Complex.Circle
public import Mathlib.Analysis.Normed.Module.Convex
public import Mathlib.Analysis.Convex.Topology
public import Mathlib.GroupTheory.QuotientGroup.Basic
public import Mathlib.CategoryTheory.Category.ULift
public import Mathlib.CategoryTheory.Comma.Arrow
public import Mathlib.CategoryTheory.Whiskering
public import Mathlib.CategoryTheory.Limits.Shapes.Pullback.IsPullback.Defs
public import Mathlib.CategoryTheory.CommSq
public import Mathlib.CategoryTheory.Limits.Shapes.Pullback.IsPullback.Basic
public import Mathlib.Topology.MetricSpace.Basic
public import Mathlib.Tactic
public import Mathlib.CategoryTheory.Category.Basic
public import Mathlib.CategoryTheory.Category.Cat
public import Mathlib.Topology.Homotopy.Basic
public import Mathlib.Topology.Homotopy.Path
public import Mathlib.CategoryTheory.ConcreteCategory.Basic
public import Mathlib.CategoryTheory.ConcreteCategory.Forget
public import Mathlib.CategoryTheory.Elementwise
public import Mathlib.AlgebraicTopology.FundamentalGroupoid.Basic
public import Mathlib.CategoryTheory.EqToHom
public import Mathlib.Topology.LocallyConstant.Basic
public import Mathlib.Topology.CompactOpen
public import Mathlib.Topology.Homotopy.Equiv
public import Mathlib.Topology.Separation.Hausdorff

@[expose] public section

/-! Source module: FiniteGraphFreeGroup.Proof -/
section Standalone_FiniteGraphFreeGroup_Proof

/-
Adapted minimal arbitrary-graph interface from Arthur742Ramos/finite-graph-fundamental-group
commit dd57e3ab8bc5a7042fcc5498e778b008d87ac032, Apache-2.0.
Finite-rank spanning-tree/counting wrappers are intentionally excluded.
-/

open CategoryTheory Quiver
noncomputable section
universe u
namespace FiniteGraphFreeGroup
class WeaklyConnected (V : Type u) [Quiver.{u} V] : Prop where
  path : ∀ a b : V,
    Nonempty (@Quiver.Path (Symmetrify V) (Quiver.symmetrifyQuiver V) a b)
abbrev graphFundamentalGroup {V : Type u} [Quiver.{u} V] (root : V) :=
  End ((Quiver.FreeGroupoid.of V).obj root)
/-- An arborescence cannot contain an edge and its formal reverse. -/
lemma no_reverse_edges {V : Type u} [Quiver.{u} V]
    (T : WideSubquiver (Symmetrify V)) [hT : @Arborescence T T.quiver]
    {a b : V} (e : @Quiver.Hom V _ a b)
    (h₁ : T a b (Sum.inl e)) (h₂ : T b a (Sum.inr e)) : False := by
  let p : @Quiver.Path T T.quiver hT.root a := (hT.uniquePath a).default
  let q : @Quiver.Path T T.quiver hT.root b := (hT.uniquePath b).default
  let f : @Quiver.Hom T T.quiver a b := ⟨Sum.inl e, h₁⟩
  let g : @Quiver.Hom T T.quiver b a := ⟨Sum.inr e, h₂⟩
  have hpq : q = p.cons f := ((hT.uniquePath b).uniq _).symm
  have hqp : p = q.cons g := ((hT.uniquePath a).uniq _).symm
  have hpq_len : q.length = p.length + 1 :=
    congrArg (@Quiver.Path.length T T.quiver hT.root b) hpq
  have hqp_len : p.length = q.length + 1 :=
    congrArg (@Quiver.Path.length T T.quiver hT.root a) hqp
  omega
end FiniteGraphFreeGroup
end
end Standalone_FiniteGraphFreeGroup_Proof

/-! Source module: FiniteGraphFreeGroup.Realization -/
section Standalone_FiniteGraphFreeGroup_Realization



open Set Function
open CategoryTheory CategoryTheory.SingleObj Quiver
open unitInterval

noncomputable section

universe u

namespace FiniteGraphFreeGroup

/-!
# A geometric realization of an arbitrary quiver

The combinatorial development works with a quiver and its free groupoid.  The
construction in this file supplies the missing topological object: every
directed edge gets a copy of the unit interval, and its two endpoints are
identified with the source and target vertices.  Parallel edges and loops are
kept as distinct interval cells.

The quotient topology is the standard weak topology on this arbitrary one-
dimensional cell complex.  The fundamental-group comparison is developed in
the later lemmas; the definitions here are intentionally independent of any
choice of spanning tree.
-/

/-- The disjoint union of discrete vertices and one interval for each edge. -/
abbrev graphRealizationPre (V : Type u) [Quiver.{u} V] :=
  WithDiscreteTopology V ⊕
    Σ _e : WithDiscreteTopology (Quiver.Total V), I

abbrev graphDiscreteVertex {V : Type u} (v : V) : WithDiscreteTopology V :=
  WithTopology.toTopology (⊥ : TopologicalSpace V) v

abbrev graphDiscreteEdge {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    WithDiscreteTopology (Quiver.Total V) :=
  WithTopology.toTopology (⊥ : TopologicalSpace (Quiver.Total V)) e

abbrev graphVertexUnderlying {V : Type u} (v : WithDiscreteTopology V) : V :=
  WithTopology.ofTopology v

abbrev graphEdgeUnderlying {V : Type u} [Quiver.{u} V]
    (e : WithDiscreteTopology (Quiver.Total V)) : Quiver.Total V :=
  WithTopology.ofTopology e

/-- The endpoint identifications used to form the geometric realization. -/
inductive graphRealizationGenerator {V : Type u} [Quiver.{u} V] :
    graphRealizationPre V → graphRealizationPre V → Prop
  | source (e : Quiver.Total V) :
      graphRealizationGenerator
        (Sum.inr ⟨graphDiscreteEdge e, 0⟩) (Sum.inl (graphDiscreteVertex e.left))
  | target (e : Quiver.Total V) :
      graphRealizationGenerator
        (Sum.inr ⟨graphDiscreteEdge e, 1⟩) (Sum.inl (graphDiscreteVertex e.right))

/-- The equivalence relation generated by the two endpoint identifications. -/
instance graphRealizationSetoid {V : Type u} [Quiver.{u} V] :
    Setoid (graphRealizationPre V) :=
  Relation.EqvGen.setoid (graphRealizationGenerator (V := V))

/-! The endpoint label is an invariant of the quotient relation.  Besides
    separating vertices, this records why no edge cell is accidentally glued
    to a vertex away from its two prescribed endpoints. -/

def graphRealizationEndpointLabel {V : Type u} [Quiver.{u} V]
    : graphRealizationPre V → Option V
  | Sum.inl v => some (graphVertexUnderlying v)
  | Sum.inr ⟨e, t⟩ =>
      if t = 0 then some (graphEdgeUnderlying e).left
      else if t = 1 then some (graphEdgeUnderlying e).right
      else none

lemma graphRealizationGenerator_endpointLabel {V : Type u} [Quiver.{u} V]
    {x y : graphRealizationPre V}
    (h : graphRealizationGenerator x y) :
  graphRealizationEndpointLabel x = graphRealizationEndpointLabel y := by
  cases h <;> simp [graphRealizationEndpointLabel, graphVertexUnderlying,
    graphEdgeUnderlying]

lemma graphRealization_eqvGen_endpointLabel {V : Type u} [Quiver.{u} V]
    {x y : graphRealizationPre V}
    (h : Relation.EqvGen (graphRealizationGenerator (V := V)) x y) :
    graphRealizationEndpointLabel x = graphRealizationEndpointLabel y := by
  induction h with
  | rel x y h => exact graphRealizationGenerator_endpointLabel h
  | refl x => rfl
  | symm x y h ih => exact ih.symm
  | trans x y z hxy hyz ihxy ihyz => exact ihxy.trans ihyz

/-- The geometric realization of an arbitrary directed multigraph. -/
abbrev graphRealization (V : Type u) [Quiver.{u} V] :=
  Quotient (graphRealizationSetoid (V := V))

/-- The quotient map from the disjoint union of cells. -/
abbrev graphRealizationQuotient {V : Type u} [Quiver.{u} V] :
    graphRealizationPre V → graphRealization V :=
  Quotient.mk'

/-- The point of the realization corresponding to a vertex. -/
def graphVertex {V : Type u} [Quiver.{u} V] (v : V) : graphRealization V :=
  graphRealizationQuotient (Sum.inl (graphDiscreteVertex v))

/-- The endpoint label descends to the quotient as a set-theoretic invariant. -/
def graphRealizationEndpointLabelQuotient {V : Type u} [Quiver.{u} V] :
    graphRealization V → Option V :=
  Quotient.lift graphRealizationEndpointLabel
    (fun _ _ h => graphRealization_eqvGen_endpointLabel h)

@[simp]
theorem graphRealizationEndpointLabelQuotient_mk {V : Type u} [Quiver.{u} V]
    (x : graphRealizationPre V) :
    graphRealizationEndpointLabelQuotient (graphRealizationQuotient x) =
      graphRealizationEndpointLabel x := rfl

@[simp]
theorem graphRealizationEndpointLabelQuotient_vertex {V : Type u} [Quiver.{u} V]
    (v : V) :
    graphRealizationEndpointLabelQuotient (graphVertex v) = some v := by
  rfl

theorem graphRealization_isOpen_iff {V : Type u} [Quiver.{u} V]
    {s : Set (graphRealization V)} :
    IsOpen s ↔ IsOpen (graphRealizationQuotient ⁻¹' s) := by
  exact isOpen_coinduced

theorem graphRealization_image_preimage_eq_of_saturated
    {V : Type u} [Quiver.{u} V] {s : Set (graphRealizationPre V)}
    (hs : ∀ {x y : graphRealizationPre V},
      Relation.EqvGen (graphRealizationGenerator (V := V)) x y →
        (x ∈ s ↔ y ∈ s)) :
    graphRealizationQuotient ⁻¹' (graphRealizationQuotient '' s) = s := by
  ext x
  constructor
  · rintro ⟨y, hy, hxy⟩
    exact (hs (Quotient.exact hxy)).mp hy
  · intro hx
    exact ⟨x, hx, rfl⟩

theorem graphRealization_image_isOpen_of_saturated
    {V : Type u} [Quiver.{u} V] {s : Set (graphRealizationPre V)}
    (hs : ∀ {x y : graphRealizationPre V},
      Relation.EqvGen (graphRealizationGenerator (V := V)) x y →
        (x ∈ s ↔ y ∈ s))
    (hopen : IsOpen s) :
    IsOpen (graphRealizationQuotient '' s) := by
  rw [graphRealization_isOpen_iff,
    graphRealization_image_preimage_eq_of_saturated hs]
  exact hopen

/-- The characteristic path of the interval cell associated to an edge. -/
def graphEdgePath {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    C(I, graphRealization V) where
  toFun t := graphRealizationQuotient (Sum.inr ⟨graphDiscreteEdge e, t⟩)
  continuous_toFun :=
    continuous_quotient_mk'.comp <|
      continuous_inr.comp
        (continuous_sigmaMk (i := graphDiscreteEdge e))

@[simp]
theorem graphRealizationQuotient_vertex {V : Type u} [Quiver.{u} V] (v : V) :
    graphRealizationQuotient (Sum.inl (graphDiscreteVertex v)) = graphVertex v := rfl

@[simp]
theorem graphEdgePath_zero {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    graphEdgePath e 0 = graphVertex e.left := by
  exact Quotient.sound (Relation.EqvGen.rel _ _ (graphRealizationGenerator.source e))

@[simp]
theorem graphEdgePath_one {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    graphEdgePath e 1 = graphVertex e.right := by
  exact Quotient.sound (Relation.EqvGen.rel _ _ (graphRealizationGenerator.target e))

theorem graphRealization_edge_interior_ne_vertex {V : Type u} [Quiver.{u} V]
    (e : Quiver.Total V) {t : I} (ht0 : t ≠ 0) (ht1 : t ≠ 1) (v : V) :
    graphRealizationQuotient (Sum.inr ⟨graphDiscreteEdge e, t⟩) ≠ graphVertex v := by
  intro h
  have hlabel := congrArg graphRealizationEndpointLabelQuotient h
  simp [graphRealizationEndpointLabelQuotient_mk,
    graphRealizationEndpointLabel, ht0, ht1] at hlabel

theorem continuous_graphEdgePath {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    Continuous (graphEdgePath e) :=
  (graphEdgePath e).continuous

/-- The interval cell, regarded as a path from the source to the target. -/
def graphRealizationForwardPath {V : Type u} [Quiver.{u} V]
    {a b : V} (e : a ⟶ b) :
    Path (graphVertex a) (graphVertex b) where
  toContinuousMap := graphEdgePath ⟨a, b, e⟩
  source' := graphEdgePath_zero ⟨a, b, e⟩
  target' := graphEdgePath_one ⟨a, b, e⟩

/-- A continuous parametrisation of the part of an interval cell from `t` to
    its source endpoint. -/
def graphEdgeRetraction (t : I) : C(I, I) where
  toFun s :=
    ⟨(1 - (s : ℝ)) * (t : ℝ),
      unitInterval.mul_mem
        ⟨unitInterval.one_minus_nonneg s, unitInterval.one_minus_le_one s⟩ t.2⟩
  continuous_toFun := by fun_prop

@[simp]
theorem graphEdgeRetraction_zero (t : I) : graphEdgeRetraction t 0 = t := by
  apply Subtype.ext
  simp [graphEdgeRetraction]

@[simp]
theorem graphEdgeRetraction_one (t : I) : graphEdgeRetraction t 1 = 0 := by
  apply Subtype.ext
  simp [graphEdgeRetraction]

def graphEdgePathToSource {V : Type u} [Quiver.{u} V]
    (e : Quiver.Total V) (t : I) :
    Path (graphEdgePath e t) (graphVertex e.left) where
  toContinuousMap := (graphEdgePath e).comp (graphEdgeRetraction t)
  source' := by simp
  target' := by simp

theorem graphRealizationPre_join_vertex {V : Type u} [Quiver.{u} V]
    (x : graphRealizationPre V) :
    ∃ v : V, Joined (graphRealizationQuotient x) (graphVertex v) := by
  cases x with
  | inl v =>
      refine ⟨graphVertexUnderlying v, ?_⟩
      exact ⟨Path.refl _⟩
  | inr z =>
      rcases z with ⟨e, t⟩
      refine ⟨(graphEdgeUnderlying e).left, ?_⟩
      refine ⟨?path⟩
      simpa [graphEdgePath, graphEdgeUnderlying, graphDiscreteEdge] using
        (graphEdgePathToSource (graphEdgeUnderlying e) t)

/-! The symmetrified quiver is the combinatorial source used by the free
    groupoid.  Its positive arrows use the characteristic interval in the
    forward direction, while its negative arrows use the same interval in
    reverse. -/

def graphRealizationSymmetricEdgePath {V : Type u} [Quiver.{u} V]
    {a b : V} (e : (Quiver.symmetrifyQuiver V).Hom a b) :
    Path (graphVertex (V := V) a) (graphVertex (V := V) b) :=
  match e with
  | Sum.inl e => graphRealizationForwardPath e
  | Sum.inr e => (graphRealizationForwardPath e).symm

def graphRealizationQuiverPath {V : Type u} [Quiver.{u} V]
    {a b : V}
    (p : @Quiver.Path (Quiver.Symmetrify V)
      (Quiver.symmetrifyQuiver V) a b) :
    Path (graphVertex (V := V) a) (graphVertex (V := V) b) := by
  induction p with
  | nil => exact Path.refl _
  | cons p e ih => exact ih.trans (graphRealizationSymmetricEdgePath e)

theorem graphRealizationQuiverPath_nil {V : Type u} [Quiver.{u} V]
    (a : V) :
    graphRealizationQuiverPath
      (Quiver.Path.nil : @Quiver.Path (Quiver.Symmetrify V)
        (Quiver.symmetrifyQuiver V) a a) = Path.refl (graphVertex a) := rfl

theorem graphRealization_pathConnected {V : Type u} [Quiver.{u} V]
    [WeaklyConnected V] (root : V) :
    PathConnectedSpace (graphRealization V) where
  nonempty := ⟨graphVertex root⟩
  joined x y := by
    refine Quotient.inductionOn₂ x y ?_
    intro x y
    rcases graphRealizationPre_join_vertex x with ⟨a, hxa⟩
    rcases graphRealizationPre_join_vertex y with ⟨b, hyb⟩
    rcases WeaklyConnected.path a b with ⟨p⟩
    exact ⟨hxa.somePath.trans ((graphRealizationQuiverPath p).trans hyb.somePath.symm)⟩

def graphRealizationQuiverMap {V : Type u} [Quiver.{u} V] :
    V ⥤q FundamentalGroupoid (graphRealization V) where
  obj v := FundamentalGroupoid.mk (graphVertex v)
  map e := FundamentalGroupoid.fromPath
    (Path.Homotopic.Quotient.mk (graphRealizationForwardPath e))

/-! The universal property of Mathlib's free groupoid produces the canonical
    functor from the combinatorial graph groupoid into the topological
    fundamental groupoid of the realization. -/

def graphFreeGroupoidToTopological {V : Type u} [Quiver.{u} V] :
    Quiver.FreeGroupoid V ⥤ FundamentalGroupoid (graphRealization V) :=
  Quiver.FreeGroupoid.lift (graphRealizationQuiverMap (V := V))

theorem graphFreeGroupoidToTopological_restrict {V : Type u} [Quiver.{u} V] :
    (Quiver.FreeGroupoid.of V ⋙q
      (graphFreeGroupoidToTopological (V := V)).toPrefunctor) =
      graphRealizationQuiverMap (V := V) := by
  exact Quiver.FreeGroupoid.lift_spec (graphRealizationQuiverMap (V := V))

/-! A quiver map acts on the realization cell by cell.  This is the map used
    below for the realization of the path-lifting cover. -/

def graphRealizationPreMap {V W : Type u} [Quiver.{u} V] [Quiver.{u} W]
    (F : V ⥤q W) : graphRealizationPre V → graphRealizationPre W :=
  Sum.elim
    (fun v => Sum.inl (graphDiscreteVertex (F.obj (graphVertexUnderlying v))))
    (fun z =>
      let e := graphEdgeUnderlying z.1
      Sum.inr ⟨graphDiscreteEdge ⟨F.obj e.left, F.obj e.right, F.map e.hom⟩, z.2⟩)

theorem graphRealizationPreMap_generator {V W : Type u} [Quiver.{u} V]
    [Quiver.{u} W] (F : V ⥤q W) {x y : graphRealizationPre V}
    (h : graphRealizationGenerator x y) :
    graphRealizationGenerator (graphRealizationPreMap F x)
      (graphRealizationPreMap F y) := by
  cases h with
  | source e =>
      exact graphRealizationGenerator.source
        ⟨F.obj e.left, F.obj e.right, F.map e.hom⟩
  | target e =>
      exact graphRealizationGenerator.target
        ⟨F.obj e.left, F.obj e.right, F.map e.hom⟩

theorem graphRealizationPreMap_eqvGen {V W : Type u} [Quiver.{u} V]
    [Quiver.{u} W] (F : V ⥤q W) {x y : graphRealizationPre V}
    (h : Relation.EqvGen (graphRealizationGenerator (V := V)) x y) :
    Relation.EqvGen (graphRealizationGenerator (V := W))
      (graphRealizationPreMap F x) (graphRealizationPreMap F y) := by
  induction h with
  | rel x y h => exact Relation.EqvGen.rel _ _ (graphRealizationPreMap_generator F h)
  | refl x => exact Relation.EqvGen.refl _
  | symm x y h ih => exact Relation.EqvGen.symm _ _ ih
  | trans x y z hxy hyz ihxy ihyz => exact Relation.EqvGen.trans _ _ _ ihxy ihyz

def graphRealizationMap {V W : Type u} [Quiver.{u} V] [Quiver.{u} W]
    (F : V ⥤q W) : graphRealization V → graphRealization W := by
  let f : graphRealizationPre V → graphRealization W :=
    fun x => graphRealizationQuotient (graphRealizationPreMap F x)
  refine Quotient.lift f (fun x y h => ?_)
  exact Quotient.sound (graphRealizationPreMap_eqvGen F h)

theorem continuous_graphRealizationMap {V W : Type u} [Quiver.{u} V]
    [Quiver.{u} W] (F : V ⥤q W) :
    Continuous (graphRealizationMap F) := by
  let f : graphRealizationPre V → graphRealization W :=
    fun x => graphRealizationQuotient (graphRealizationPreMap F x)
  have hcont : Continuous (graphRealizationPreMap F) := by
    apply continuous_sumElim.2
    constructor
    · exact continuous_inl.comp continuous_of_discreteTopology
    · apply continuous_inr.comp
      apply continuous_sigma
      intro e
      change Continuous (fun t : I =>
        (⟨graphDiscreteEdge
            ⟨F.obj (graphEdgeUnderlying e).left,
              F.obj (graphEdgeUnderlying e).right,
              F.map (graphEdgeUnderlying e).hom⟩, t⟩ :
          Σ _e : WithDiscreteTopology (Quiver.Total W), I))
      exact (continuous_sigmaMk (i := graphDiscreteEdge
        ⟨F.obj (graphEdgeUnderlying e).left,
          F.obj (graphEdgeUnderlying e).right,
          F.map (graphEdgeUnderlying e).hom⟩)).comp continuous_id
  have hf : Continuous f := continuous_quotient_mk'.comp hcont
  change Continuous (Quotient.lift f _)
  apply hf.quotient_lift

@[simp]
theorem graphRealizationMap_vertex {V W : Type u} [Quiver.{u} V]
    [Quiver.{u} W] (F : V ⥤q W) (v : V) :
    graphRealizationMap F (graphVertex v) = graphVertex (F.obj v) := by
  rfl

@[simp]
theorem graphRealizationMap_edgePath {V W : Type u} [Quiver.{u} V]
    [Quiver.{u} W] (F : V ⥤q W) (e : Quiver.Total V) (t : I) :
    graphRealizationMap F (graphEdgePath e t) =
      graphEdgePath ⟨F.obj e.left, F.obj e.right, F.map e.hom⟩ t := by
  rfl

theorem graphRealizationMap_forwardPath {V W : Type u} [Quiver.{u} V]
    [Quiver.{u} W] (F : V ⥤q W) {a b : V} (e : a ⟶ b) :
    (graphRealizationMap F) ∘ (graphRealizationForwardPath e) =
      graphRealizationForwardPath (F.map e) := by
  ext t
  rfl

/-! Taking the endomorphism group at a chosen vertex gives the canonical
    comparison homomorphism on fundamental groups.  The present file proves
    its construction and its behavior on edge generators; an isomorphism
    theorem requires the separate topological normal-form argument for paths
    in an arbitrary one-dimensional cell complex. -/

def graphCombinatorialToTopological {V : Type u} [Quiver.{u} V]
    (root : V) :
    graphFundamentalGroup root →*
      FundamentalGroup (graphRealization V) (graphVertex root) :=
  (graphFreeGroupoidToTopological (V := V)).mapEnd _

/-! The geometric basepoint change is available independently of the still
    open comparison-isomorphism theorem. -/

noncomputable def graphTopologicalRootEquiv {V : Type u} [Quiver.{u} V]
    [WeaklyConnected V] (root₁ root₂ : V) :
    FundamentalGroup (graphRealization V) (graphVertex root₁) ≃*
      FundamentalGroup (graphRealization V) (graphVertex root₂) := by
  letI : PathConnectedSpace (graphRealization V) :=
    graphRealization_pathConnected root₁
  exact FundamentalGroup.fundamentalGroupMulEquivOfPathConnected
    (graphVertex root₁) (graphVertex root₂)

theorem graphVertex_injective {V : Type u} [Quiver.{u} V]
    {v w : V} (h : graphVertex v = graphVertex w) : v = w := by
  have h' := Quotient.exact h
  exact Option.some.inj <|
    graphRealization_eqvGen_endpointLabel h'

theorem graphVertex_injective_iff {V : Type u} [Quiver.{u} V]
    {v w : V} : graphVertex v = graphVertex w ↔ v = w := by
  exact ⟨graphVertex_injective, congrArg graphVertex⟩

end FiniteGraphFreeGroup
end
end Standalone_FiniteGraphFreeGroup_Realization

/-! Source module: PresentationComplex.BouquetConstruction -/
section Standalone_PresentationComplex_BouquetConstruction



/-!
# The arbitrary bouquet and its canonical free-group generators

The vertex is universe-correct even when the generator type is not small.
The topology is exactly the weak endpoint quotient in `graphRealization`.
-/

open CategoryTheory Quiver

set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false

noncomputable section
universe u
namespace PresentationComplex

/-- The single vertex, in the same universe as the edge labels. -/
def Vertex (S : Type u) : Type u := PUnit

instance (S : Type u) : Inhabited (Vertex S) := ⟨PUnit.unit⟩
instance (S : Type u) : Subsingleton (Vertex S) := inferInstanceAs (Subsingleton PUnit)

instance (S : Type u) : Quiver.{u} (Vertex S) where
  Hom _ _ := S

instance (S : Type u) : FiniteGraphFreeGroup.WeaklyConnected (Vertex S) where
  path a b := by
    have h : a = b := Subsingleton.elim _ _
    subst b
    exact ⟨Quiver.Path.nil⟩

/-- The total edge indices of the one-vertex graph are exactly its labels. -/
def edgeIndexEquiv (S : Type u) : Quiver.Total (Vertex S) ≃ S where
  toFun e := e.hom
  invFun s := ⟨default, default, s⟩
  left_inv := by
    rintro ⟨a, b, s⟩
    cases a
    cases b
    rfl
  right_inv _ := rfl

/-- The actual endpoint quotient of one vertex and one interval for each label. -/
abbrev Bouquet (S : Type u) := FiniteGraphFreeGroup.graphRealization (Vertex S)

/-- The image of the unique vertex in the endpoint quotient. -/
def base (S : Type u) : Bouquet S := FiniteGraphFreeGroup.graphVertex (default : Vertex S)

/-- The actual forward traversal of the interval indexed by `s`. -/
def edgeLoop {S : Type u} (s : S) : Path (base S) (base S) :=
  FiniteGraphFreeGroup.graphRealizationForwardPath
    (show (default : Vertex S) ⟶ (default : Vertex S) from s)

instance (S : Type u) : PathConnectedSpace (Bouquet S) :=
  FiniteGraphFreeGroup.graphRealization_pathConnected (default : Vertex S)

end PresentationComplex
end
end Standalone_PresentationComplex_BouquetConstruction

/-! Source module: PresentationComplex.WordLoopConstruction -/
section Standalone_PresentationComplex_WordLoopConstruction



/-! Actual finite word loops in the arbitrary weak bouquet. Mathlib multiplies
loop classes in reverse chronological order, and this recursion respects it. -/
noncomputable section
open Set
open Path.Homotopic
universe u
namespace PresentationComplex
variable {S : Type u}

/-- The positive or negative actual traversal of a labeled interval. -/
def signedEdgeLoop (l : S × Bool) : Path (base S) (base S) :=
  if l.2 then edgeLoop l.1 else (edgeLoop l.1).symm

/-- A finite word's continuous loop, in Mathlib's multiplication convention. -/
def wordLoop : List (S × Bool) → Path (base S) (base S)
  | [] => Path.refl (base S)
  | l :: w => (wordLoop w).trans (signedEdgeLoop l)

/-- The canonical finite representative chosen with classical equality internally. -/
def relatorWord (g : FreeGroup S) : List (S × Bool) := by
  classical
  exact g.toWord

/-- A chosen reduced representative, without any public decidable-equality hypothesis. -/
def relatorLoop (g : FreeGroup S) : Path (base S) (base S) := by
  classical
  exact wordLoop (relatorWord g)

/-- The finite set of edge labels used by this representative. -/
def wordSupport (w : List (S × Bool)) : Finset S := by
  classical
  exact (w.map Prod.fst).toFinset

/-- The explicit finite subgraph containing a word loop's whole image. -/
def wordCarrier (w : List (S × Bool)) : Set (Bouquet S) :=
  {base S} ∪ ⋃ s ∈ wordSupport w, Set.range (edgeLoop s)

theorem wordLoop_range_subset (w : List (S × Bool)) :
    Set.range (wordLoop w) ⊆ wordCarrier w := by
  classical
  induction w with
  | nil => simp [wordLoop,wordCarrier]
  | cons l w ih =>
    rw [wordLoop,Path.trans_range]
    apply union_subset
    · exact ih.trans (by
        intro x hx
        rcases hx with hx | hx
        · exact Or.inl hx
        · right
          rcases mem_iUnion.mp hx with ⟨s,hs⟩
          rcases mem_iUnion.mp hs with ⟨hs,hx⟩
          exact mem_iUnion.mpr ⟨s,mem_iUnion.mpr ⟨by
            simpa [wordSupport] using Or.inr hs,hx⟩⟩)
    · intro x hx
      right
      refine mem_iUnion.mpr ⟨l.1,mem_iUnion.mpr ⟨by simp [wordSupport],?_⟩⟩
      cases l with
      | mk s b =>
        cases b <;> simpa [signedEdgeLoop,Path.symm_range] using hx

end PresentationComplex
end
end Standalone_PresentationComplex_WordLoopConstruction

/-! Source module: CellAttachment.CircleGenerator -/
section Standalone_CellAttachment_CircleGenerator

/-
Copyright (c) 2026 Ruize Chen. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ruize Chen

This is a local backport from mathlib commit
389347a7c1cfa76f6bd5be2ca35d4cb621610ad3, file
Mathlib/Topology/Covering/FundamentalGroupCircle.lean (Apache 2.0):
https://github.com/leanprover-community/mathlib4/blob/389347a7c1cfa76f6bd5be2ca35d4cb621610ad3/Mathlib/Topology/Covering/FundamentalGroupCircle.lean
The supporting lifting lemmas below are backported from the same commit's
Mathlib/Topology/Homotopy/Lifting.lean, copyright (c) 2025 Junyan Xu.
https://github.com/leanprover-community/mathlib4/blob/389347a7c1cfa76f6bd5be2ca35d4cb621610ad3/Mathlib/Topology/Homotopy/Lifting.lean
The zmultiples equivalence is adapted, specialized to real numbers, from
Mathlib/Algebra/Group/Subgroup/ZPowers/Lemmas.lean, copyright (c) 2020
Chris Hughes, authors Chris Hughes and Snir Broshi (Apache 2.0).
https://github.com/leanprover-community/mathlib4/blob/389347a7c1cfa76f6bd5be2ca35d4cb621610ad3/Mathlib/Algebra/Group/Subgroup/ZPowers/Lemmas.lean
All additions after `end AddCircle` are project-specific.
-/




/-!
# The fundamental group of the circle

For `0 < p`, the fundamental group of `AddCircle p` at any basepoint is isomorphic to `ℤ`
(`AddCircle.windingNumberIso`). The winding number `AddCircle.windingNumber` of a loop is
`(f 1 - f 0) / p` for any continuous lift `f : I → ℝ` of the loop
(`AddCircle.windingNumber_eq_div`); in particular the loop `t ↦ n • (t * p) + x` has winding
number `n` (`AddCircle.windingNumber_zsmulLoop`).
-/


open unitInterval

noncomputable section

namespace AddSubgroup

/-- Backported real specialization of the integer-multiples equivalence. -/
def zmultiplesEquivInt {a : ℝ} (ha : a ≠ 0) : zmultiples a ≃+ ℤ :=
  ((AddMonoidHom.ofInjective (show Function.Injective (zmultiplesHom ℝ a) from
    smul_left_injective ℤ ha)).trans
    (AddEquiv.addSubgroupCongr (range_zmultiplesHom a))).symm

@[simp]
theorem coe_zmultiplesEquivInt_symm_apply {a : ℝ} (ha : a ≠ 0) (n : ℤ) :
    ((zmultiplesEquivInt ha).symm n : ℝ) = n • a := by
  simp only [zmultiplesEquivInt, AddEquiv.symm_symm, AddEquiv.trans_apply,
    AddEquiv.addSubgroupCongr_apply, AddMonoidHom.ofInjective_apply, zmultiplesHom_apply]

@[simp]
theorem zmultiplesEquivInt_apply_zsmul {a : ℝ} (ha : a ≠ 0) (n : ℤ) :
    zmultiplesEquivInt ha ⟨n • a, zsmul_mem_zmultiples a n⟩ = n :=
  (zmultiplesEquivInt ha).eq_symm_apply.mp (Subtype.ext (by simp))

end AddSubgroup

namespace IsCoveringMap

variable {E X : Type*} [TopologicalSpace E] [TopologicalSpace X] {p : E → X}
  (cov : IsCoveringMap p)

theorem coe_monodromy_mk {x y : X} (γ : Path x y) (e : p ⁻¹' {x}) :
    (cov.monodromy (.mk γ) e : E) = cov.liftPath γ e (γ.source.trans e.2.symm) 1 :=
  rfl

lemma monodromy_eq_apply_one {x y : X} {γ : Path x y} {e : p ⁻¹' {x}} {Γ : C(I, E)}
    (hpΓ : p ∘ Γ = γ) (Γ_0 : Γ 0 = e) : cov.monodromy (.mk γ) e = Γ 1 := by
  rw [show Γ = cov.liftPath γ e (γ.source.trans e.2.symm) from
    (eq_liftPath_iff' ..).mpr ⟨hpΓ, Γ_0⟩, coe_monodromy_mk]

end IsCoveringMap

namespace IsQuotientCoveringMap

variable {E X G : Type*} [TopologicalSpace E] [TopologicalSpace X]
  [Group G] [MulAction G E] {p : E → X} (hp : IsQuotientCoveringMap p G)
  {x : X} (e : p ⁻¹' {x}) {γ : FundamentalGroup X x} {g : G}

theorem fundamentalGroupToMulOpposite_apply_mk_eq {e : p ⁻¹' {x}}
    {γ : Path x x} {g : G} {Γ : C(I, E)}
    (hpΓ : p ∘ Γ = γ) (Γ_0 : Γ 0 = e) (Γ_1 : Γ 1 = g • e) :
    hp.fundamentalGroupToMulOpposite e (.mk γ) = .op g :=
  hp.fundamentalGroupToMulOpposite_apply_eq_Iff.mpr <| by
    simp [hp.isCoveringMap.monodromy_eq_apply_one hpΓ Γ_0, Γ_1]

theorem fundamentalGroupToMulOpposite_toPermFiber :
    hp.fundamentalGroupToMulOpposite (hp.toPermFiber x g e) γ =
      MulOpposite.op (g * (hp.fundamentalGroupToMulOpposite e γ).unop * g⁻¹) := by
  rw [fundamentalGroupToMulOpposite_apply_eq_Iff, hp.monodromy_toPermFiber]
  simp only [MulOpposite.unop_op, toPermFiber_apply_apply_coe,
    ← hp.unop_fundamentalGroupToMulOpposite_smul, mul_smul, inv_smul_smul]

theorem fundamentalGroupToMulOpposite_eq [IsMulCommutative G] (e' : p ⁻¹' {x}) :
    hp.fundamentalGroupToMulOpposite e = hp.fundamentalGroupToMulOpposite e' := by
  obtain ⟨g, rfl⟩ := hp.exists_toPermFiber_eq e e'
  ext γ
  rw [fundamentalGroupToMulOpposite_toPermFiber, mul_comm' g, mul_inv_cancel_right,
    MulOpposite.op_unop]

theorem fundamentalGroupEquiv_eq [SimplyConnectedSpace E] [IsMulCommutative G]
    (e' : p ⁻¹' {x}) : hp.fundamentalGroupEquiv e = hp.fundamentalGroupEquiv e' :=
  MulEquiv.ext fun γ ↦ congr($(hp.fundamentalGroupToMulOpposite_eq e e') γ)

end IsQuotientCoveringMap

namespace IsAddQuotientCoveringMap

variable {E X G : Type*} [TopologicalSpace E] [TopologicalSpace X]
  [AddGroup G] [AddAction G E] {p : E → X} (hp : IsAddQuotientCoveringMap p G)
  {x : X} (e : p ⁻¹' {x})

theorem fundamentalGroupToMulOpposite_apply_mk_eq {e : p ⁻¹' {x}}
    {γ : Path x x} {g : Multiplicative G}
    {Γ : C(I, E)} (hpΓ : p ∘ Γ = γ) (Γ_0 : Γ 0 = e) (Γ_1 : Γ 1 = g • e) :
    hp.fundamentalGroupToMulOpposite e (.mk γ) = .op g :=
  hp.toMultiplicative.fundamentalGroupToMulOpposite_apply_mk_eq hpΓ Γ_0 Γ_1

theorem fundamentalGroupEquiv_eq [SimplyConnectedSpace E] [IsAddCommutative G]
    (e' : p ⁻¹' {x}) : hp.fundamentalGroupEquiv e = hp.fundamentalGroupEquiv e' := by
  let : IsMulCommutative (Multiplicative G) := ⟨⟨fun a b =>
    congrArg Multiplicative.ofAdd (add_comm' a.toAdd b.toAdd)⟩⟩
  exact
  hp.toMultiplicative.fundamentalGroupEquiv_eq e e'

end IsAddQuotientCoveringMap

namespace AddCircle

variable (p : ℝ)

/-- The loop in `AddCircle p` based at `x` that winds `n` times, defined as
`t ↦ n • (t * p) + x`. -/
def zsmulLoop (x : ℝ) (n : ℤ) : Path (x : AddCircle p) x where
  toFun t := n • (t * p : ℝ) + x
  source' := by simp
  target' := by simp [coe_period]
  continuous_toFun := by fun_prop

@[simp]
theorem zsmulLoop_apply (x : ℝ) (n : ℤ) (t : I) :
    zsmulLoop p x n t = n • (t * p : ℝ) + x :=
  rfl

variable {p} [hp : Fact (0 < p)]

/-- **The fundamental group of the circle is `ℤ`**: the isomorphism sends the class of a loop to
its winding number (`windingNumber_eq_div`). It does not depend on the choice of a lift of the
basepoint (`IsAddQuotientCoveringMap.fundamentalGroupEquiv_eq`). -/
noncomputable def windingNumberIso (x : AddCircle p) :
    FundamentalGroup (AddCircle p) x ≃* Multiplicative ℤ :=
  ((isAddQuotientCoveringMap_coe p).fundamentalGroupEquiv (x := x)
      ⟨(equivIco p 0 x : ℝ), coe_equivIco⟩).trans <|
    MulOpposite.opMulEquiv.symm.trans (AddSubgroup.zmultiplesEquivInt hp.out.ne').toMultiplicative

/-- The winding number of a loop in `AddCircle p`, defined as its image under `windingNumberIso`. -/
noncomputable def windingNumber {x : AddCircle p} (γ : FundamentalGroup (AddCircle p) x) : ℤ :=
  (windingNumberIso x γ).toAdd

/-- The winding number of a loop in `AddCircle p` is `(f 1 - f 0) / p`, for any continuous lift
`f` of the loop to `ℝ`. -/
theorem windingNumber_eq_div {x : AddCircle p} (γ : Path x x) (f : C(I, ℝ)) (hf : (↑) ∘ f = γ) :
    (windingNumber (.mk γ) : ℝ) = (f 1 - f 0) / p := by
  have h0 : (f 0 : AddCircle p) = x := congr($hf 0).trans γ.source
  obtain ⟨n, hn⟩ : ∃ n : ℤ, n • p = f 1 - f 0 :=
    AddSubgroup.mem_zmultiples_iff.mp <| QuotientAddGroup.eq_iff_sub_mem.mp <|
      congr($hf 1).trans <| γ.target.trans h0.symm
  have h : (isAddQuotientCoveringMap_coe p).fundamentalGroupEquiv (x := x) ⟨f 0, h0⟩ (.mk γ) =
      .op (.ofAdd ⟨n • p, n, rfl⟩) :=
    (isAddQuotientCoveringMap_coe p).fundamentalGroupToMulOpposite_apply_mk_eq hf rfl (by simp [hn])
  simp [windingNumber, windingNumberIso, AddSubgroup.zmultiplesEquivInt_apply_zsmul hp.out.ne' n,
    (isAddQuotientCoveringMap_coe p).fundamentalGroupEquiv_eq _ ⟨f 0, h0⟩, h,
    eq_div_iff hp.out.ne', ← zsmul_eq_mul, ← hn]

/-- The loop `t ↦ n • (t * p) + x` has winding number `n`. -/
theorem windingNumber_zsmulLoop (x : ℝ) (n : ℤ) :
    windingNumber (x := x) (.mk (zsmulLoop p x n)) = n := by
  simpa [hp.out.ne'] using windingNumber_eq_div (zsmulLoop p x n)
    ⟨fun t ↦ n • (t * p) + x, by fun_prop⟩ rfl

end AddCircle

/-! ## Project-specific concrete circle generator -/

namespace CellAttachment

/-- The standard positively oriented circle loop, `t ↦ exp(2πt)`, based at `1`. -/
def circleGenerator : Path (1 : Circle) 1 where
  toFun t := Circle.exp ((t : ℝ) * (2 * Real.pi))
  source' := by simp
  target' := by simp
  continuous_toFun := by fun_prop

@[simp]
theorem circleGenerator_apply (t : I) :
    circleGenerator t = Circle.exp ((t : ℝ) * (2 * Real.pi)) := rfl

/-- The corresponding homotopy class in the actual fundamental group. -/
def circleGeneratorClass : FundamentalGroup Circle (1 : Circle) :=
  .mk circleGenerator

/-- The complex unit circle fundamental group, identified with the integers by lifting
through the real exponential covering. -/
def circleFundamentalGroupEquivInt :
    FundamentalGroup Circle (1 : Circle) ≃* Multiplicative ℤ :=
  (Circle.isAddQuotientCoveringMap_exp.fundamentalGroupEquiv
    ⟨0, Circle.exp_zero⟩).trans <|
    MulOpposite.opMulEquiv.symm.trans
      (AddSubgroup.zmultiplesEquivInt (by positivity : (2 * Real.pi : ℝ) ≠ 0)).toMultiplicative

@[simp]
theorem circleFundamentalGroupEquivInt_generator :
    circleFundamentalGroupEquivInt circleGeneratorClass = Multiplicative.ofAdd (1 : ℤ) := by
  have h : Circle.isAddQuotientCoveringMap_exp.fundamentalGroupEquiv
      ⟨0, Circle.exp_zero⟩ circleGeneratorClass =
        .op (.ofAdd ⟨(1 : ℤ) • (2 * Real.pi), 1, rfl⟩) := by
    exact Circle.isAddQuotientCoveringMap_exp.fundamentalGroupToMulOpposite_apply_mk_eq
      (Γ := ⟨fun t => (t : ℝ) * (2 * Real.pi), by fun_prop⟩) rfl (by simp) (by simp)
  change Multiplicative.ofAdd
    (AddSubgroup.zmultiplesEquivInt (by positivity : (2 * Real.pi : ℝ) ≠ 0)
      (MulOpposite.unop
        (Circle.isAddQuotientCoveringMap_exp.fundamentalGroupEquiv
          ⟨0, Circle.exp_zero⟩ circleGeneratorClass)).toAdd) = _
  rw [h]
  exact congrArg Multiplicative.ofAdd (AddSubgroup.zmultiplesEquivInt_apply_zsmul
    (by positivity : (2 * Real.pi : ℝ) ≠ 0) 1)

/-- Every actual based homotopy class on the complex unit circle is an integer power of
the standard loop. This is the generator fact needed for attaching two-cells. -/
theorem circleGenerator_generates (γ : FundamentalGroup Circle (1 : Circle)) :
    ∃ n : ℤ, circleGeneratorClass ^ n = γ := by
  refine ⟨(circleFundamentalGroupEquivInt γ).toAdd, ?_⟩
  apply circleFundamentalGroupEquivInt.injective
  rw [map_zpow, circleFundamentalGroupEquivInt_generator]
  change (circleFundamentalGroupEquivInt γ).toAdd • (1 : ℤ) =
    (circleFundamentalGroupEquivInt γ).toAdd
  simp

/-- The cyclic subgroup generated by the standard circle loop is the whole fundamental group. -/
theorem circleGenerator_zpowers_eq_top :
    Subgroup.zpowers circleGeneratorClass = ⊤ := by
  apply top_unique
  intro γ _
  exact circleGenerator_generates γ

/-- `AddCircle (2π)` and the complex unit circle are the same circle model. -/
def additiveCircleIdentification : AddCircle (2 * Real.pi) ≃ₜ Circle :=
  AddCircle.homeomorphCircle'

@[simp]
theorem additiveCircleIdentification_zero :
    additiveCircleIdentification (0 : AddCircle (2 * Real.pi)) = (1 : Circle) := by
  change Circle.exp 0 = 1
  simp

/-- Mapping the additive generator through the standard homeomorphism gives precisely
the standard complex-circle loop, with its basepoints explicitly identified. -/
theorem additiveCircle_generator_identification :
    ((AddCircle.zsmulLoop (2 * Real.pi) 0 1).map
      additiveCircleIdentification.continuous).cast
        additiveCircleIdentification_zero.symm additiveCircleIdentification_zero.symm =
      circleGenerator := by
  apply Path.ext
  funext t
  change AddCircle.homeomorphCircle'
    ((1 : ℤ) • ((t : ℝ) * (2 * Real.pi)) + (0 : ℝ) : ℝ) =
      Circle.exp ((t : ℝ) * (2 * Real.pi))
  simp [AddCircle.homeomorphCircle'_apply_mk]

end CellAttachment
end
end Standalone_CellAttachment_CircleGenerator

/-! Source module: PresentationComplex.LoopCircle -/
section Standalone_PresentationComplex_LoopCircle



/-! Descending an actual based loop to the actual complex circle. -/
noncomputable section
open unitInterval
open Set
universe u
namespace PresentationComplex
variable {X : Type u} [TopologicalSpace X] {x₀ : X}

def circleFromPeriod : AddCircle (1 : ℝ) ≃ₜ Circle :=
  AddCircle.homeomorphCircle one_ne_zero

/-- The endpoint-identified interval descent, transported to the actual complex unit circle. -/
def loopCircleMap (p : Path x₀ x₀) : C(Circle, X) where
  toFun z := AddCircle.liftIco (1 : ℝ) 0 p.extend (circleFromPeriod.symm z)
  continuous_toFun :=
    (AddCircle.liftIco_zero_continuous (by simp) p.continuous_extend.continuousOn).comp
      circleFromPeriod.symm.continuous

theorem circleFromPeriod_generator (t : I) :
    circleFromPeriod (t.val : AddCircle (1 : ℝ)) = CellAttachment.circleGenerator t := by
  rw [circleFromPeriod, AddCircle.homeomorphCircle_apply, AddCircle.toCircle_apply_mk,
    CellAttachment.circleGenerator_apply]
  congr 1
  ring

/-- Pointwise compatibility with the actual unit-speed generating circle loop. -/
theorem loopCircleMap_generator (p : Path x₀ x₀) (t : I) :
    loopCircleMap p (CellAttachment.circleGenerator t) = p t := by
  rw [← circleFromPeriod_generator]
  change AddCircle.liftIco (1 : ℝ) 0 p.extend
    (circleFromPeriod.symm (circleFromPeriod (t.val : AddCircle (1 : ℝ)))) = p t
  rw [circleFromPeriod.symm_apply_apply]
  by_cases ht : t.val < 1
  · rw [AddCircle.liftIco_zero_coe_apply ⟨t.property.1,ht⟩]
    exact p.extend_apply t.property
  · have heq : t = 1 := Subtype.ext (le_antisymm t.property.2 (le_of_not_gt ht))
    subst t
    change AddCircle.liftIco (1 : ℝ) 0 p.extend ((1 : ℝ) : AddCircle (1 : ℝ)) = p 1
    rw [AddCircle.coe_period]
    rw [← AddCircle.coe_zero, AddCircle.liftIco_zero_coe_apply (by norm_num)]
    simp

@[simp] theorem loopCircleMap_one (p : Path x₀ x₀) : loopCircleMap p 1 = x₀ := by
  simpa only [Path.source] using loopCircleMap_generator p 0

end PresentationComplex

namespace PresentationComplex
open Set
variable {X : Type u} [TopologicalSpace X] {x₀ : X}

/-- Descending to the circle does not enlarge a loop's image. -/
theorem loopCircleMap_range_subset (p : Path x₀ x₀) :
    Set.range (loopCircleMap p) ⊆ Set.range p := by
  rintro _ ⟨z,rfl⟩
  let t := AddCircle.equivIco (1 : ℝ) 0 (circleFromPeriod.symm z)
  have ht : t.val ∈ Set.Icc (0 : ℝ) 1 := by
    exact ⟨t.property.1, by simpa using t.property.2.le⟩
  refine ⟨⟨t.val,ht⟩,?_⟩
  exact (p.extend_apply ht).symm

end PresentationComplex
end
end Standalone_PresentationComplex_LoopCircle

/-! Source module: CellAttachment.Adjunction -/
section Standalone_CellAttachment_Adjunction




/-!
# Genuine adjunction space for an arbitrary family of two-cells

The carrier is the quotient of the topological disjoint union of the original
space and the indexed closed complex unit disks. The relation is generated by
exactly the prescribed boundary identifications; the topology is the quotient
topology. No separation or finiteness assumptions are used.
-/

noncomputable section

namespace CellAttachment

universe u v

/-- The closed two-dimensional unit disk in the complex plane. -/
abbrev Disk := {z : ℂ // ‖z‖ ≤ 1}

/-- The inclusion of the unit circle into the closed disk. -/
def boundaryInclusion : C(Circle, Disk) where
  toFun z := ⟨z, le_of_eq (Circle.norm_coe z)⟩
  continuous_toFun := by fun_prop

/-- The actual topological disjoint union before attaching the disks. -/
abbrev Raw (X : Type u) (ι : Type v) := X ⊕ (Σ _ : ι, Disk)

variable {X : Type u} [TopologicalSpace X] {ι : Type v}

/-- Only boundary points are identified with their prescribed attaching images. -/
inductive AttachingRel (f : ι → C(Circle, X)) : Raw X ι → Raw X ι → Prop
  | boundary (i : ι) (z : Circle) :
      AttachingRel f (.inr ⟨i, boundaryInclusion z⟩) (.inl (f i z))

/-- The adjunction quotient, with its induced quotient topology. -/
def Space (f : ι → C(Circle, X)) := Quot (AttachingRel f)

instance (f : ι → C(Circle, X)) : TopologicalSpace (Space f) :=
  inferInstanceAs (TopologicalSpace (Quot (AttachingRel f)))

/-- The quotient map from the unglued topological disjoint union. -/
def quotientMap (f : ι → C(Circle, X)) : C(Raw X ι, Space f) :=
  ⟨Quot.mk _, continuous_quot_mk⟩

/-- The actual continuous inclusion of the original space. -/
def inclusion (f : ι → C(Circle, X)) : C(X, Space f) where
  toFun x := quotientMap f (.inl x)
  continuous_toFun := (quotientMap f).continuous.comp continuous_inl

/-- The characteristic map of an attached closed disk. -/
def characteristic (f : ι → C(Circle, X)) (i : ι) : C(Disk, Space f) where
  toFun z := quotientMap f (.inr ⟨i, z⟩)
  continuous_toFun := (quotientMap f).continuous.comp
    (continuous_inr.comp (continuous_sigmaMk (i := i)))

@[simp] theorem characteristic_boundary (f : ι → C(Circle, X)) (i : ι) (z : Circle) :
    characteristic f i (boundaryInclusion z) = inclusion f (f i z) :=
  Quot.sound (.boundary i z)

/-- The quotient map is a quotient map, not merely a continuous surjection. -/
theorem quotientMap_isQuotientMap (f : ι → C(Circle, X)) :
    Topology.IsQuotientMap (quotientMap f) := isQuotientMap_quot_mk

/-- Identify the boundary point of a disk with a circle point. -/
def diskBoundaryPoint (z : Disk) (h : ‖(z : ℂ)‖ = 1) : Circle :=
  ⟨z, mem_sphere_zero_iff_norm.mpr h⟩

/-- An algebraic invariant used only to distinguish points of the original space.
It is deliberately not asserted to be continuous. -/
def baseValue (f : ι → C(Circle, X)) : Raw X ι → Option X
  | .inl x => some x
  | .inr ⟨i, z⟩ => if h : ‖(z : ℂ)‖ = 1 then some (f i (diskBoundaryPoint z h)) else none

theorem baseValue_respects (f : ι → C(Circle, X)) {a b : Raw X ι}
    (h : AttachingRel f a b) : baseValue f a = baseValue f b := by
  cases h with
  | boundary i z =>
    change (if h : ‖(z : ℂ)‖ = 1 then some (f i (diskBoundaryPoint (boundaryInclusion z) h)) else none) = some (f i z)
    rw [dite_eq_left (Circle.norm_coe z)]
    rfl

/-- Algebraic readout of the base value descends through precisely the attaching relation. -/
def quotientBaseValue (f : ι → C(Circle, X)) : Space f → Option X :=
  Quot.lift (baseValue f) (fun _ _ h => baseValue_respects f h)

/-- The attaching quotient never identifies two distinct original points. -/
theorem inclusion_injective (f : ι → C(Circle, X)) : Function.Injective (inclusion f) := by
  intro x y h
  have h' := congrArg (quotientBaseValue f) h
  exact Option.some.inj h'

/-- The specified map on fundamental groups is induced by the actual inclusion. -/
def inclusionPi1 (f : ι → C(Circle, X)) (x₀ : X) :
    FundamentalGroup X x₀ →* FundamentalGroup (Space f) (inclusion f x₀) :=
  FundamentalGroup.map (inclusion f) x₀

end CellAttachment
end
end Standalone_CellAttachment_Adjunction

/-! Source module: PresentationComplex.Connected -/
section Standalone_PresentationComplex_Connected



/-! Genuine path connectedness of arbitrary disk adjunctions. -/
noncomputable section
open Set Metric
namespace PresentationComplex
universe u v
variable {X : Type u} [TopologicalSpace X] {R : Type v}

theorem disk_pathConnected : PathConnectedSpace CellAttachment.Disk := by
  have h : IsPathConnected (closedBall (0 : ℂ) 1) :=
    (convex_closedBall (0 : ℂ) 1).isPathConnected ⟨0, by simp⟩
  have hd : (closedBall (0 : ℂ) 1) = {z : ℂ | ‖z‖ ≤ 1} := by
    ext z
    simp only [mem_closedBall, dist_zero_right, mem_setOf_eq]
  rw [hd] at h
  exact isPathConnected_iff_pathConnectedSpace.mp h

/-- Attaching any family of actual disks to a nonempty path-connected base
preserves actual continuous-path connectedness, even for empty/duplicate families. -/
theorem attachment_pathConnected (f : R → C(Circle, X)) (x₀ : X)
    [PathConnectedSpace X] : PathConnectedSpace (CellAttachment.Space f) := by
  letI : PathConnectedSpace CellAttachment.Disk := disk_pathConnected
  have hjoin : ∀ y : CellAttachment.Space f,
      Joined y (CellAttachment.inclusion f x₀) := by
    intro y
    obtain ⟨a,rfl⟩ := (CellAttachment.quotientMap_isQuotientMap f).surjective y
    cases a with
    | inl x =>
      exact ⟨(PathConnectedSpace.somePath x x₀).map
        (CellAttachment.inclusion f).continuous⟩
    | inr w =>
      rcases w with ⟨i,z⟩
      have p : Joined (CellAttachment.characteristic f i z)
          (CellAttachment.inclusion f (f i 1)) := by
        rw [← CellAttachment.characteristic_boundary f i 1]
        exact ⟨(PathConnectedSpace.somePath z (CellAttachment.boundaryInclusion 1)).map
          (CellAttachment.characteristic f i).continuous⟩
      exact p.trans ⟨(PathConnectedSpace.somePath (f i 1) x₀).map
        (CellAttachment.inclusion f).continuous⟩
  exact ⟨⟨CellAttachment.inclusion f x₀⟩, fun x y => (hjoin x).trans (hjoin y).symm⟩

end PresentationComplex
end
end Standalone_PresentationComplex_Connected

/-! Source module: CellAttachment.GroupQuotient -/
section Standalone_CellAttachment_GroupQuotient




/-!
# Algebraic quotient tools for cell attachment

This file contains only group-theoretic results. In particular, it does not assume or
claim that any topological attachment induces a surjective fundamental-group map or
has a specified kernel. Once those geometric assertions have been established, the
results here produce the quotient equivalence and its compatibility with the map.
-/

namespace CellAttachment

universe u v w

variable {G : Type u} [Group G] {H : Type v} [Group H] {ι : Type w}

/-- Killing every member of a family is equivalent to killing its normal closure. -/
theorem normalClosure_range_le_ker_iff (r : ι → G) (f : G →* H) :
    Subgroup.normalClosure (Set.range r) ≤ f.ker ↔ ∀ i, f (r i) = 1 := by
  constructor
  · intro h i
    exact MonoidHom.mem_ker.mp (h (Subgroup.subset_normalClosure (Set.mem_range_self i)))
  · intro h
    apply Subgroup.normalClosure_le_normal
    rintro _ ⟨i, rfl⟩
    exact MonoidHom.mem_ker.mpr (h i)

/-- A homomorphism killing the relators descends to the quotient by their normal closure. -/
def liftNormalClosure (r : ι → G) (f : G →* H) (h : ∀ i, f (r i) = 1) :
    G ⧸ Subgroup.normalClosure (Set.range r) →* H :=
  QuotientGroup.lift _ f ((normalClosure_range_le_ker_iff r f).mpr h)

@[simp]
theorem liftNormalClosure_mk (r : ι → G) (f : G →* H) (h : ∀ i, f (r i) = 1)
    (g : G) :
    liftNormalClosure r f h (QuotientGroup.mk' (Subgroup.normalClosure (Set.range r)) g) =
      f g := rfl

/-- The descended homomorphism commutes with the quotient projection. -/
@[simp]
theorem liftNormalClosure_comp_mk (r : ι → G) (f : G →* H) (h : ∀ i, f (r i) = 1) :
    (liftNormalClosure r f h).comp
      (QuotientGroup.mk' (Subgroup.normalClosure (Set.range r))) = f := rfl

/-- The descended homomorphism is uniquely determined by this compatibility. -/
theorem liftNormalClosure_unique (r : ι → G) (f : G →* H) (h : ∀ i, f (r i) = 1)
    (k : G ⧸ Subgroup.normalClosure (Set.range r) →* H)
    (hk : k.comp (QuotientGroup.mk' (Subgroup.normalClosure (Set.range r))) = f) :
    k = liftNormalClosure r f h := by
  apply QuotientGroup.monoidHom_ext
  rw [hk, liftNormalClosure_comp_mk]

/-- The compatible first-isomorphism equivalence, after a surjective map and its
kernel have been identified by a separate argument. -/
noncomputable def quotientNormalClosureEquiv (r : ι → G) (f : G →* H)
    (hf : Function.Surjective f) (hker : f.ker = Subgroup.normalClosure (Set.range r)) :
    G ⧸ Subgroup.normalClosure (Set.range r) ≃* H :=
  QuotientGroup.liftEquiv _ hf hker.symm

@[simp]
theorem quotientNormalClosureEquiv_mk (r : ι → G) (f : G →* H)
    (hf : Function.Surjective f) (hker : f.ker = Subgroup.normalClosure (Set.range r))
    (g : G) :
    quotientNormalClosureEquiv r f hf hker
      (QuotientGroup.mk' (Subgroup.normalClosure (Set.range r)) g) = f g := rfl

/-- Compatibility in homomorphism form, suitable for a commutative diagram. -/
@[simp]
theorem quotientNormalClosureEquiv_comp_mk (r : ι → G) (f : G →* H)
    (hf : Function.Surjective f) (hker : f.ker = Subgroup.normalClosure (Set.range r)) :
    (quotientNormalClosureEquiv r f hf hker).toMonoidHom.comp
      (QuotientGroup.mk' (Subgroup.normalClosure (Set.range r))) = f := rfl

/-- Exactness identifies precisely which elements the original map kills. -/
theorem map_eq_one_iff_mem_normalClosure (r : ι → G) (f : G →* H)
    (hker : f.ker = Subgroup.normalClosure (Set.range r)) (g : G) :
    f g = 1 ↔ g ∈ Subgroup.normalClosure (Set.range r) := by
  rw [← hker]
  exact MonoidHom.mem_ker.symm

/-- Independently replacing the generators by conjugate elements does not change
normal closure. This is the algebraic part of independence from whiskering paths. -/
theorem normalClosure_range_eq_of_isConj (r s : ι → G)
    (h : ∀ i, IsConj (r i) (s i)) :
    Subgroup.normalClosure (Set.range r) = Subgroup.normalClosure (Set.range s) := by
  apply le_antisymm
  · apply Subgroup.normalClosure_le_normal
    rintro _ ⟨i, rfl⟩
    exact Subgroup.conjugatesOfSet_subset_normalClosure
      (Group.mem_conjugatesOfSet_iff.mpr ⟨s i, Set.mem_range_self i, (h i).symm⟩)
  · apply Subgroup.normalClosure_le_normal
    rintro _ ⟨i, rfl⟩
    exact Subgroup.conjugatesOfSet_subset_normalClosure
      (Group.mem_conjugatesOfSet_iff.mpr ⟨r i, Set.mem_range_self i, h i⟩)

/-- A separate conjugating element may be chosen for every generator. -/
theorem normalClosure_range_conjugate (r c : ι → G) :
    Subgroup.normalClosure (Set.range (fun i => c i * r i * (c i)⁻¹)) =
      Subgroup.normalClosure (Set.range r) := by
  symm
  apply normalClosure_range_eq_of_isConj
  intro i
  exact isConj_iff.mpr ⟨c i, rfl⟩

/-- The normal closure is also independent of the orientation of all generators. -/
theorem normalClosure_range_inverse (r : ι → G) :
    Subgroup.normalClosure (Set.range (fun i => (r i)⁻¹)) =
      Subgroup.normalClosure (Set.range r) := by
  apply le_antisymm
  · apply Subgroup.normalClosure_le_normal
    rintro _ ⟨i, rfl⟩
    exact (Subgroup.normalClosure (Set.range r)).inv_mem
      (Subgroup.subset_normalClosure (Set.mem_range_self i))
  · apply Subgroup.normalClosure_le_normal
    rintro _ ⟨i, rfl⟩
    have h : (r i)⁻¹ ∈ Subgroup.normalClosure (Set.range (fun j => (r j)⁻¹)) :=
      Subgroup.subset_normalClosure (Set.mem_range_self i)
    exact (Subgroup.inv_mem_iff _).mp h

/-- Changing independently chosen conjugating paths induces the identity-on-
representatives equivalence between the corresponding quotient groups. -/
def quotientNormalClosureConjugateEquiv (r c : ι → G) :
    G ⧸ Subgroup.normalClosure (Set.range (fun i => c i * r i * (c i)⁻¹)) ≃*
      G ⧸ Subgroup.normalClosure (Set.range r) :=
  QuotientGroup.quotientMulEquivOfEq (normalClosure_range_conjugate r c)

@[simp]
theorem quotientNormalClosureConjugateEquiv_mk (r c : ι → G) (g : G) :
    quotientNormalClosureConjugateEquiv r c
      (QuotientGroup.mk' (Subgroup.normalClosure
        (Set.range (fun i => c i * r i * (c i)⁻¹))) g) =
      QuotientGroup.mk' (Subgroup.normalClosure (Set.range r)) g := rfl

end CellAttachment
end Standalone_CellAttachment_GroupQuotient

/-! Source module: CellAttachment.Statement -/
section Standalone_CellAttachment_Statement




/-!
# Exact target: attaching any family of two-cells

This module fixes the theorem statement before the geometric proof is assembled.
It contains definitions and no asserted or admitted cell-attachment theorem.
-/

noncomputable section
namespace CellAttachment
universe u v

variable {X : Type u} [TopologicalSpace X] {ι : Type v}

/-- The actual attaching loop in X, whiskered chronologically from the basepoint
along a chosen path, around the attaching circle once, and back. -/
def attachingLoop (f : ι → C(Circle, X)) (x₀ : X)
    (γ : ∀ i, Path x₀ (f i 1)) (i : ι) : Path x₀ x₀ :=
  (γ i).trans ((circleGenerator.map (f i).continuous).trans (γ i).symm)

/-- Its class in Mathlib's ordinary continuous-path fundamental group. -/
def attachingLoopClass (f : ι → C(Circle, X)) (x₀ : X)
    (γ : ∀ i, Path x₀ (f i 1)) : ι → FundamentalGroup X x₀ :=
  fun i => .mk (attachingLoop f x₀ γ i)

/-- Precisely the normal subgroup generated by the chosen conjugated attaching loops. -/
def attachingNormalClosure (f : ι → C(Circle, X)) (x₀ : X)
    (γ : ∀ i, Path x₀ (f i 1)) : Subgroup (FundamentalGroup X x₀) :=
  Subgroup.normalClosure (Set.range (attachingLoopClass f x₀ γ))

instance attachingNormalClosure_normal (f : ι → C(Circle, X)) (x₀ : X)
    (γ : ∀ i, Path x₀ (f i 1)) : (attachingNormalClosure f x₀ γ).Normal := by
  unfold attachingNormalClosure
  infer_instance

/-- The full arbitrary-family two-cell attachment theorem, including compatibility
of the quotient equivalence with the actual inclusion-induced map. The index
universe and the space universe are independent. -/
def completeStatement : Prop :=
  ∀ {X : Type u} [TopologicalSpace X] [PathConnectedSpace X] {ι : Type v}
    (f : ι → C(Circle, X)) (x₀ : X) (γ : ∀ i, Path x₀ (f i 1)),
    Function.Surjective (inclusionPi1 f x₀) ∧
    (inclusionPi1 f x₀).ker = attachingNormalClosure f x₀ γ ∧
    ∃ e : FundamentalGroup X x₀ ⧸ attachingNormalClosure f x₀ γ ≃*
      FundamentalGroup (Space f) (inclusion f x₀),
      e.toMonoidHom.comp (QuotientGroup.mk' (attachingNormalClosure f x₀ γ)) =
        inclusionPi1 f x₀

end CellAttachment
end
end Standalone_CellAttachment_Statement

/-! Source module: PresentationComplex.RelatorConstruction -/
section Standalone_PresentationComplex_RelatorConstruction



/-! Genuine circle maps and disk adjunction for arbitrary presentations. -/
noncomputable section
open Set Path.Homotopic
universe u v
namespace PresentationComplex
variable {S : Type u} {R : Type v}

/-- Every relator's finite word loop descends continuously to the actual circle. -/
def relatorMap (r : R → FreeGroup S) : R → C(Circle, Bouquet S) :=
  fun i => loopCircleMap (relatorLoop (r i))

@[simp] theorem relatorMap_one (r : R → FreeGroup S) (i : R) :
    relatorMap r i 1 = base S := loopCircleMap_one _

/-- The genuine boundary-generated quotient of the bouquet and indexed closed disks. -/
abbrev Space (r : R → FreeGroup S) := CellAttachment.Space (relatorMap r)

/-- The actual continuous bouquet inclusion. -/
def inclusion (r : R → FreeGroup S) : C(Bouquet S, Space r) :=
  CellAttachment.inclusion (relatorMap r)

/-- The actual image of the bouquet vertex. -/
def point (r : R → FreeGroup S) : Space r := inclusion r (base S)

instance (r : R → FreeGroup S) : PathConnectedSpace (Space r) :=
  attachment_pathConnected (relatorMap r) (base S)

/-- The constant based anchoring path to the attaching circle's based image. -/
def anchorPath (r : R → FreeGroup S) (i : R) :
    Path (base S) (relatorMap r i 1) :=
  (Path.refl (base S)).cast rfl (relatorMap_one r i)

/-- Each individual disk boundary lies in a finite bouquet subgraph. -/
theorem relatorMap_range_subset (r : R → FreeGroup S) (i : R) :
    Set.range (relatorMap r i) ⊆ wordCarrier (relatorWord (r i)) := by
  classical
  exact (loopCircleMap_range_subset (relatorLoop (r i))).trans
    (wordLoop_range_subset (relatorWord (r i)))

/-- The exact subgroup of the free group imposed by the presentation. -/
def relatorNormalClosure (r : R → FreeGroup S) : Subgroup (FreeGroup S) :=
  Subgroup.normalClosure (Set.range r)

instance relatorNormalClosure_normal (r : R → FreeGroup S) :
    (relatorNormalClosure r).Normal := by
  unfold relatorNormalClosure
  infer_instance

end PresentationComplex
end
end Standalone_PresentationComplex_RelatorConstruction

/-! Source module: PresentationComplex.EveryGroupConstruction -/
section Standalone_PresentationComplex_EveryGroupConstruction



/-! Construction-only data for the every-group realization challenge.
No CW structure, Hausdorffness, or fundamental-group realization proof is imported. -/
noncomputable section
universe u
namespace PresentationComplex
variable (G : Type u) [Group G]

/-- One relator for every multiplication table entry, plus the identity generator. -/
def groupRelators : (G × G) ⊕ PUnit.{u+1} → FreeGroup G
  | Sum.inl (g,h) => FreeGroup.of g * FreeGroup.of h * (FreeGroup.of (g*h))⁻¹
  | Sum.inr _ => FreeGroup.of (1 : G)


/-- The actual complex associated to the multiplication-and-identity presentation. -/
abbrev EveryGroupSpace (G : Type u) [Group G] := Space (groupRelators G)

/-- Its actual distinguished zero-cell. -/
def everyGroupPoint (G : Type u) [Group G] : EveryGroupSpace G := point (groupRelators G)

end PresentationComplex
end
end Standalone_PresentationComplex_EveryGroupConstruction
