/-
Arbitrary presentation complexes and the genuine Hausdorff CW realization of every group.
Mathematical source: Allen Hatcher, Algebraic Topology, Corollary 1.28.
Authors: Arthur Freitas Ramos, David Barros Hulak,
Ruy Jose Guerra Barretto de Queiroz.
First-party source: Apache-2.0. Reused source notices are retained below.
Generated by scripts/generate_standalone.py; edit the modular sources instead.
-/
/-
Apache-2.0 license for first-party and Apache-licensed reused sources.

                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.

      "License" shall mean the terms and conditions for use, reproduction,
      and distribution as defined by Sections 1 through 9 of this document.

      "Licensor" shall mean the copyright owner or entity authorized by
      the copyright owner that is granting the License.

      "Legal Entity" shall mean the union of the acting entity and all
      other entities that control, are controlled by, or are under common
      control with that entity. For the purposes of this definition,
      "control" means (i) the power, direct or indirect, to cause the
      direction or management of such entity, whether by contract or
      otherwise, or (ii) ownership of fifty percent (50%) or more of the
      outstanding shares, or (iii) beneficial ownership of such entity.

      "You" (or "Your") shall mean an individual or Legal Entity
      exercising permissions granted by this License.

      "Source" form shall mean the preferred form for making modifications,
      including but not limited to software source code, documentation
      source, and configuration files.

      "Object" form shall mean any form resulting from mechanical
      transformation or translation of a Source form, including but
      not limited to compiled object code, generated documentation,
      and conversions to other media types.

      "Work" shall mean the work of authorship, whether in Source or
      Object form, made available under the License, as indicated by a
      copyright notice that is included in or attached to the work
      (an example is provided in the Appendix below).

      "Derivative Works" shall mean any work, whether in Source or Object
      form, that is based on (or derived from) the Work and for which the
      editorial revisions, annotations, elaborations, or other modifications
      represent, as a whole, an original work of authorship. For the purposes
      of this License, Derivative Works shall not include works that remain
      separable from, or merely link (or bind by name) to the interfaces of,
      the Work and Derivative Works thereof.

      "Contribution" shall mean any work of authorship, including
      the original version of the Work and any modifications or additions
      to that Work or Derivative Works thereof, that is intentionally
      submitted to Licensor for inclusion in the Work by the copyright owner
      or by an individual or Legal Entity authorized to submit on behalf of
      the copyright owner. For the purposes of this definition, "submitted"
      means any form of electronic, verbal, or written communication sent
      to the Licensor or its representatives, including but not limited to
      communication on electronic mailing lists, source code control systems,
      and issue tracking systems that are managed by, or on behalf of, the
      Licensor for the purpose of discussing and improving the Work, but
      excluding communication that is conspicuously marked or otherwise
      designated in writing by the copyright owner as "Not a Contribution."

      "Contributor" shall mean Licensor and any individual or Legal Entity
      on behalf of whom a Contribution has been received by Licensor and
      subsequently incorporated within the Work.

   2. Grant of Copyright License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      copyright license to reproduce, prepare Derivative Works of,
      publicly display, publicly perform, sublicense, and distribute the
      Work and such Derivative Works in Source or Object form.

   3. Grant of Patent License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      (except as stated in this section) patent license to make, have made,
      use, offer to sell, sell, import, and otherwise transfer the Work,
      where such license applies only to those patent claims licensable
      by such Contributor that are necessarily infringed by their
      Contribution(s) alone or by combination of their Contribution(s)
      with the Work to which such Contribution(s) was submitted. If You
      institute patent litigation against any entity (including a
      cross-claim or counterclaim in a lawsuit) alleging that the Work
      or a Contribution incorporated within the Work constitutes direct
      or contributory patent infringement, then any patent licenses
      granted to You under this License for that Work shall terminate
      as of the date such litigation is filed.

   4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and

      (b) You must cause any modified files to carry prominent notices
          stating that You changed the files; and

      (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work,
          excluding those notices that do not pertain to any part of
          the Derivative Works; and

      (d) If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.

      You may add Your own copyright statement to Your modifications and
      may provide additional or different license terms and conditions
      for use, reproduction, or distribution of Your modifications, or
      for any such Derivative Works as a whole, provided Your use,
      reproduction, and distribution of the Work otherwise complies with
      the conditions stated in this License.

   5. Submission of Contributions. Unless You explicitly state otherwise,
      any Contribution intentionally submitted for inclusion in the Work
      by You to the Licensor shall be under the terms and conditions of
      this License, without any additional terms or conditions.
      Notwithstanding the above, nothing herein shall supersede or modify
      the terms of any separate license agreement you may have executed
      with Licensor regarding such Contributions.

   6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work and reproducing the content of the NOTICE file.

   7. Disclaimer of Warranty. Unless required by applicable law or
      agreed to in writing, Licensor provides the Work (and each
      Contributor provides its Contributions) on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
      implied, including, without limitation, any warranties or conditions
      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
      PARTICULAR PURPOSE. You are solely responsible for determining the
      appropriateness of using or redistributing the Work and assume any
      risks associated with Your exercise of permissions under this License.

   8. Limitation of Liability. In no event and under no legal theory,
      whether in tort (including negligence), contract, or otherwise,
      unless required by applicable law (such as deliberate and grossly
      negligent acts) or agreed to in writing, shall any Contributor be
      liable to You for damages, including any direct, indirect, special,
      incidental, or consequential damages of any character arising as a
      result of this License or out of the use or inability to use the
      Work (including but not limited to damages for loss of goodwill,
      work stoppage, computer failure or malfunction, or any and all
      other commercial damages or losses), even if such Contributor
      has been advised of the possibility of such damages.

   9. Accepting Warranty or Additional Liability. While redistributing
      the Work or Derivative Works thereof, You may choose to offer,
      and charge a fee for, acceptance of support, warranty, indemnity,
      or other liability obligations and/or rights consistent with this
      License. However, in accepting such obligations, You may act only
      on Your own behalf and on Your sole responsibility, not on behalf
      of any other Contributor, and only if You agree to indemnify,
      defend, and hold each Contributor harmless for any liability
      incurred by, or claims asserted against, such Contributor by reason
      of your accepting any such warranty or additional liability.

   END OF TERMS AND CONDITIONS

   APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

   Copyright 2026 Arthur Freitas Ramos

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

-/
/-
Vendored directed-topology helpers retain this MIT notice.
Copyright 2023 Dominique Lawson

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-/
module

public import PresentationPackage.Proof2

@[expose] public section

/-! Source module: CellAttachment.EquivalenceExactness -/
section Standalone_CellAttachment_EquivalenceExactness




/-! # Transport of actual map exactness along a compatible group equivalence -/

namespace CellAttachment
universe u v w z
variable {G : Type u} {H : Type v} {K : Type w} {ι : Type z}
variable [Group G] [Group H] [Group K]

/-- The normal closure of a family transports under an actual group equivalence. -/
theorem mem_normalClosure_range_equiv (e : G ≃* H) (r : ι → G) (g : G) :
    e g ∈ Subgroup.normalClosure (Set.range (fun i => e (r i))) ↔
      g ∈ Subgroup.normalClosure (Set.range r) := by
  have hm := Subgroup.map_normalClosure (Set.range r) e.toMonoidHom e.surjective
  have hs : e.toMonoidHom '' Set.range r = Set.range (fun i => e (r i)) := by
    ext h
    simp
  rw [hs] at hm
  rw [← hm, Subgroup.mem_map]
  constructor
  · rintro ⟨a,ha,hag⟩
    exact e.injective hag ▸ ha
  · intro hg
    exact ⟨g,hg,rfl⟩

/-- Surjectivity and the precise kernel transport through a genuine compatible equivalence. -/
theorem exact_comp_equiv (e : G ≃* H) (r : ι → G) (p : H →* K)
    (hp : Function.Surjective p)
    (hker : p.ker = Subgroup.normalClosure (Set.range (fun i => e (r i)))) :
    Function.Surjective (p.comp e.toMonoidHom) ∧
      (p.comp e.toMonoidHom).ker = Subgroup.normalClosure (Set.range r) := by
  constructor
  · exact hp.comp e.surjective
  · ext g
    change p (e g) = 1 ↔ g ∈ Subgroup.normalClosure (Set.range r)
    rw [← MonoidHom.mem_ker, hker]
    exact mem_normalClosure_range_equiv e r g

end CellAttachment
end Standalone_CellAttachment_EquivalenceExactness

/-! Source module: CellAttachment.Main -/
section Standalone_CellAttachment_Main




/-!
# Attaching an arbitrary family of two-cells

The theorem concerns the genuine boundary-generated topological quotient and the
actual inclusion-induced map. All disk, annulus, retraction, cover and groupoid
pushout data are constructed in the imported proof modules.
-/

noncomputable section
set_option backward.isDefEq.respectTransparency false
namespace CellAttachment
universe u v
variable {X : Type u} [TopologicalSpace X] {ι : Type v}

/-- The actual arbitrary-family cell attachment induces a surjective fundamental-group
map, with exactly the normal closure of the specified whiskered attaching loops as kernel. -/
theorem cell_attachment_exact (f : ι → C(Circle, X)) (x₀ : X) [PathConnectedSpace X]
    (γ : ∀ i, Path x₀ (f i 1)) :
    Function.Surjective (inclusionPi1 f x₀) ∧
      (inclusionPi1 f x₀).ker = attachingNormalClosure f x₀ γ := by
  let p := chosenAttachmentAnchorPath f x₀ γ
  obtain ⟨hs,hk,_⟩ := neighborhood_inclusion_vertex_quotient f x₀ p
  let e := neighborhoodPi1Equiv f x₀
  let r := attachingLoopClass f x₀ γ
  let F := FundamentalGroup.map (neighborhoodToSpace f) (neighborhoodInclusion f x₀)
  have hR : (fun i => e (r i)) = neighborhoodTransportedRelator f x₀ p := by
    funext i
    rw [neighborhoodTransportedRelator_path]
    exact neighborhoodPi1Equiv_attachingLoopClass f x₀ γ i
  have hk' : F.ker = Subgroup.normalClosure (Set.range (fun i => e (r i))) := by
    rw [hR]
    exact hk
  obtain ⟨hSurj,hKer⟩ := exact_comp_equiv e r F hs hk'
  have hFactor : F.comp e.toMonoidHom = inclusionPi1 f x₀ :=
    inclusionPi1_factorization f x₀
  rw [hFactor] at hSurj hKer
  exact ⟨hSurj,hKer⟩

/-- Full two-cell attachment theorem, including the inclusion-compatible quotient
isomorphism, for arbitrary independent space/index universes. -/
theorem two_cell_attachment : completeStatement.{u,v} := by
  intro X _ _ ι f x₀ γ
  obtain ⟨hs,hk⟩ := cell_attachment_exact f x₀ γ
  refine ⟨hs,hk,?_⟩
  refine ⟨quotientNormalClosureEquiv (attachingLoopClass f x₀ γ) (inclusionPi1 f x₀)
    hs hk, ?_⟩
  rfl

end CellAttachment
end
end Standalone_CellAttachment_Main

/-! Source module: PresentationComplex.FundamentalGroup -/
section Standalone_PresentationComplex_FundamentalGroup



/-! The exact ordinary path-based fundamental group of the genuine quotient,
with literal bouquet-inclusion and generator compatibility. -/
noncomputable section
open Path.Homotopic
universe u v
namespace PresentationComplex
variable {S : Type u} {R : Type v}

/-- The actual inclusion-induced map, preceded by the proved bouquet equivalence. -/
def presentationMap (r : R → FreeGroup S) : FreeGroup S →*
    FundamentalGroup (Space r) (point r) :=
  (CellAttachment.inclusionPi1 (relatorMap r) (base S)).comp
    (freeGroupEquiv S).toMonoidHom

/-- The actual quotient inclusion is surjective with precisely the prescribed relators. -/
theorem presentationMap_exact (r : R → FreeGroup S) :
    Function.Surjective (presentationMap r) ∧
      (presentationMap r).ker = relatorNormalClosure r := by
  obtain ⟨hs,hk⟩ := CellAttachment.cell_attachment_exact
    (relatorMap r) (base S) (anchorPath r)
  have hrel : CellAttachment.attachingLoopClass (relatorMap r) (base S) (anchorPath r) =
      fun i => freeGroupEquiv S (r i) := funext (attachingLoopClass_eq r)
  have hk' : (CellAttachment.inclusionPi1 (relatorMap r) (base S)).ker =
      Subgroup.normalClosure (Set.range (fun i => freeGroupEquiv S (r i))) := by
    simpa only [CellAttachment.attachingNormalClosure,hrel] using hk
  exact CellAttachment.exact_comp_equiv (freeGroupEquiv S) r
    (CellAttachment.inclusionPi1 (relatorMap r) (base S)) hs hk'

/-- The proved inclusion-compatible quotient equivalence. -/
def quotientToPresentationPi1 (r : R → FreeGroup S) :
    (FreeGroup S ⧸ relatorNormalClosure r) ≃*
      FundamentalGroup (Space r) (point r) :=
  CellAttachment.quotientNormalClosureEquiv r (presentationMap r)
    (presentationMap_exact r).1 (presentationMap_exact r).2

/-- Label actual continuous loops by the presented group. -/
def presentationPi1Equiv (r : R → FreeGroup S) :
    FundamentalGroup (Space r) (point r) ≃*
      (FreeGroup S ⧸ relatorNormalClosure r) :=
  (quotientToPresentationPi1 r).symm

/-- Compatibility with the actual bouquet inclusion, not an unspecified map. -/
theorem presentationPi1Equiv_inclusion (r : R → FreeGroup S) :
    (presentationPi1Equiv r).toMonoidHom.comp
      (CellAttachment.inclusionPi1 (relatorMap r) (base S)) =
    (QuotientGroup.mk' (relatorNormalClosure r)).comp (bouquetEquiv S).toMonoidHom := by
  ext x
  obtain ⟨w,rfl⟩ := (freeGroupEquiv S).surjective x
  change presentationPi1Equiv r (presentationMap r w) =
    QuotientGroup.mk' (relatorNormalClosure r) ((freeGroupEquiv S).symm (freeGroupEquiv S w))
  rw [(freeGroupEquiv S).symm_apply_apply]
  rw [← CellAttachment.quotientNormalClosureEquiv_mk r (presentationMap r)
    (presentationMap_exact r).1 (presentationMap_exact r).2 w]
  exact (quotientToPresentationPi1 r).symm_apply_apply _

/-- The generator indexed by s is exactly the actual forward interval loop in the quotient. -/
theorem presentationPi1Equiv_generator (r : R → FreeGroup S) (s : S) :
    presentationPi1Equiv r (Path.Homotopic.Quotient.mk ((edgeLoop s).map (inclusion r).continuous)) =
      QuotientGroup.mk' (relatorNormalClosure r) (FreeGroup.of s) := by
  have h := DFunLike.congr_fun (presentationPi1Equiv_inclusion r) (Path.Homotopic.Quotient.mk (edgeLoop s))
  change presentationPi1Equiv r
      (Path.Homotopic.Quotient.mk ((edgeLoop s).map (inclusion r).continuous)) =
    QuotientGroup.mk' (relatorNormalClosure r) (bouquetEquiv S (Path.Homotopic.Quotient.mk (edgeLoop s))) at h
  rw [bouquetEquiv_edgeLoop] at h
  exact h

end PresentationComplex
end
end Standalone_PresentationComplex_FundamentalGroup

/-! Source module: PresentationComplex.EveryGroupPresentation -/
section Standalone_PresentationComplex_EveryGroupPresentation



/-! Every group has an explicit multiplication-and-identity presentation.
This is an algebraic ingredient only; the topological realization uses the
separately constructed actual presentation complex. -/
noncomputable section
open Set
universe u
namespace PresentationComplex
variable (G : Type u) [Group G]


abbrev groupNormalClosure := Subgroup.normalClosure (Set.range (groupRelators G))
abbrev GroupPresentation := FreeGroup G ⧸ groupNormalClosure G

/-- The genuine free-group evaluation homomorphism. -/
def groupEvaluation : FreeGroup G →* G := FreeGroup.lift id

theorem groupEvaluation_relator (i : (G × G) ⊕ PUnit.{u+1}) :
    groupEvaluation G (groupRelators G i) = 1 := by
  cases i with
  | inl p => cases p; simp [groupRelators,groupEvaluation]
  | inr _ => simp [groupRelators,groupEvaluation]

/-- The quotient projection associated to this explicit presentation. -/
def groupProjection : FreeGroup G →* GroupPresentation G :=
  QuotientGroup.mk' (groupNormalClosure G)

theorem groupProjection_relator (i : (G × G) ⊕ PUnit.{u+1}) :
    groupProjection G (groupRelators G i) = 1 :=
  (QuotientGroup.eq_one_iff _).mpr
    (Subgroup.subset_normalClosure (Set.mem_range_self i))

/-- Evaluation descends because the actual specified relations evaluate to one. -/
def presentationEvaluation : GroupPresentation G →* G :=
  CellAttachment.liftNormalClosure (groupRelators G) (groupEvaluation G)
    (groupEvaluation_relator G)

/-- The inverse uses the generator indexed by each element of the group. -/
def groupToPresentation : G →* GroupPresentation G where
  toFun g := groupProjection G (FreeGroup.of g)
  map_one' := groupProjection_relator G (Sum.inr PUnit.unit)
  map_mul' g h := by
    have hk := groupProjection_relator G (Sum.inl (g,h))
    have hk' : groupProjection G (FreeGroup.of g) * groupProjection G (FreeGroup.of h) *
        (groupProjection G (FreeGroup.of (g*h)))⁻¹ = 1 := by
      simpa only [groupRelators,map_mul,map_inv] using hk
    exact (mul_inv_eq_one.mp hk').symm

@[simp] theorem presentationEvaluation_generator (g : G) :
    presentationEvaluation G (groupProjection G (FreeGroup.of g)) = g := by
  simp only [presentationEvaluation,groupProjection,
    CellAttachment.liftNormalClosure_mk,groupEvaluation,FreeGroup.lift_apply_of,id_eq]

/-- No kernel oracle: both inverse equations are proved from generators and relations. -/
def groupPresentationEquiv : GroupPresentation G ≃* G where
  toFun := presentationEvaluation G
  invFun := groupToPresentation G
  left_inv := by
    intro x
    have he : (groupToPresentation G).comp (presentationEvaluation G) =
        MonoidHom.id (GroupPresentation G) := by
      apply QuotientGroup.monoidHom_ext
      apply FreeGroup.lift.symm.injective
      funext g
      change groupToPresentation G
        (presentationEvaluation G (groupProjection G (FreeGroup.of g))) =
          groupProjection G (FreeGroup.of g)
      rw [presentationEvaluation_generator]
      rfl
    exact DFunLike.congr_fun he x
  right_inv := presentationEvaluation_generator G
  map_mul' := (presentationEvaluation G).map_mul

@[simp] theorem groupPresentationEquiv_generator (g : G) :
    groupPresentationEquiv G (groupProjection G (FreeGroup.of g)) = g :=
  presentationEvaluation_generator G g

end PresentationComplex
end
end Standalone_PresentationComplex_EveryGroupPresentation

/-! Source module: PresentationComplex.Hausdorff -/
section Standalone_PresentationComplex_Hausdorff



/-! Actual Hausdorffness of the weak bouquet and genuine disk adjunction.
Mathlib's CW class omits a Hausdorff assumption; these are independent quotient
separation proofs, so the headline uses a genuine Hausdorff CW complex. -/
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false

noncomputable section
open Set Function CategoryTheory Quiver unitInterval
open FiniteGraphFreeGroup
universe u v
namespace PresentationComplex

def Separated {X : Type*} [TopologicalSpace X] (x y : X) : Prop :=
  ∃ A B : Set X, IsOpen A ∧ IsOpen B ∧ x ∈ A ∧ y ∈ B ∧ Disjoint A B

theorem Separated.symm {X : Type*} [TopologicalSpace X] {x y : X}
    (h : Separated x y) : Separated y x := by
  rcases h with ⟨A,B,hA,hB,hx,hy,hd⟩
  exact ⟨B,A,hB,hA,hy,hx,hd.symm⟩

theorem separated_continuous {X Y : Type*} [TopologicalSpace X]
    [TopologicalSpace Y] [T2Space Y] (f : C(X,Y)) {x y : X} (h : f x ≠ f y) :
    Separated x y := by
  rcases t2_separation h with ⟨A,B,hA,hB,hx,hy,hd⟩
  exact ⟨f ⁻¹' A,f ⁻¹' B,hA.preimage f.continuous,hB.preimage f.continuous,
    hx,hy,hd.preimage _⟩

theorem separated_openEmbedding {X Y : Type*} [TopologicalSpace X]
    [TopologicalSpace Y] [T2Space X] (f : X → Y) (hf : Topology.IsOpenEmbedding f)
    {x y : X} (h : x ≠ y) : Separated (f x) (f y) := by
  rcases t2_separation h with ⟨A,B,hA,hB,hx,hy,hd⟩
  refine ⟨f '' A,f '' B,hf.isOpenMap _ hA,hf.isOpenMap _ hB,
    ⟨x,hx,rfl⟩,⟨y,hy,rfl⟩,?_⟩
  apply disjoint_left.mpr
  rintro z ⟨a,ha,he⟩ ⟨b,hb,he'⟩
  have hab : a = b := hf.injective (he.trans he'.symm)
  subst b
  exact disjoint_left.mp hd ha hb

section Bouquet
variable (S : Type u)

def rawBouquetHeight : graphRealizationPre (Vertex S) → ℝ
  | Sum.inl _ => 0
  | Sum.inr z => min z.2.val (1-z.2.val)

theorem rawBouquetHeight_respects {x y : graphRealizationPre (Vertex S)}
    (h : Relation.EqvGen (graphRealizationGenerator (V := Vertex S)) x y) :
    rawBouquetHeight S x = rawBouquetHeight S y := by
  induction h with
  | rel x y h => cases h <;> norm_num [rawBouquetHeight]
  | refl x => rfl
  | symm x y h ih => exact ih.symm
  | trans x y z hxy hyz ihxy ihyz => exact ihxy.trans ihyz

/-- A continuous height vanishing exactly at the bouquet vertex. -/
def bouquetHeight : C(Bouquet S,ℝ) where
  toFun := Quotient.lift (rawBouquetHeight S) (fun _ _ h => rawBouquetHeight_respects S h)
  continuous_toFun := by
    apply continuous_coinduced_dom.mpr
    have hc : Continuous (Sum.elim (fun _ : WithDiscreteTopology (Vertex S) => (0 : ℝ))
        (fun z : Σ _ : WithDiscreteTopology (Quiver.Total (Vertex S)), I => min z.2.val (1-z.2.val))) := by
      apply Continuous.sumElim
      · exact continuous_const
      · apply continuous_sigma
        intro e
        exact continuous_subtype_val.min (continuous_const.sub continuous_subtype_val)
    exact hc.congr (fun z => by cases z <;> rfl)

def bouquetAllInteriors : C((Σ _ : S, Ioo (0 : I) 1),Bouquet S) where
  toFun p := edgeInterior ((edgeIndexEquiv S).symm p.1) p.2
  continuous_toFun := by
    apply continuous_sigma
    intro s
    exact (edgeInterior ((edgeIndexEquiv S).symm s)).continuous

theorem bouquetAllInteriors_isOpenEmbedding :
    Topology.IsOpenEmbedding (bouquetAllInteriors S) := by
  apply Topology.IsOpenEmbedding.of_continuous_injective_isOpenMap
  · exact (bouquetAllInteriors S).continuous
  · rintro ⟨s,t⟩ ⟨s',t'⟩ h
    dsimp only [bouquetAllInteriors,ContinuousMap.coe_mk,edgeInterior] at h
    have he := graphRealization_interior_eqvGen_eq t.property.1 t.property.2
      t'.property.1 t'.property.2 (Quotient.exact h)
    have hs : s = s' := (edgeIndexEquiv S).symm.injective he.1
    subst s'
    exact Sigma.ext rfl (heq_of_eq (Subtype.ext he.2))
  · rw [isOpenMap_sigma]
    intro s
    simpa only [bouquetAllInteriors,ContinuousMap.coe_mk] using
      (edgeInterior_isOpenEmbedding ((edgeIndexEquiv S).symm s)).isOpenMap

theorem bouquet_point_cases (x : Bouquet S) :
    x = base S ∨ ∃ p, bouquetAllInteriors S p = x := by
  obtain ⟨a,rfl⟩ := Quotient.mk'_surjective x
  cases a with
  | inl v =>
    left
    exact congrArg graphVertex (Subsingleton.elim (graphVertexUnderlying v) default)
  | inr w =>
    rcases w with ⟨eb,t⟩
    let e : Quiver.Total (Vertex S) := graphEdgeUnderlying eb
    change graphEdgePath e t = base S ∨ _
    by_cases ht0 : t = 0
    · left
      rw [ht0,graphEdgePath_zero]
      exact congrArg graphVertex (Subsingleton.elim e.left default)
    by_cases ht1 : t = 1
    · left
      rw [ht1,graphEdgePath_one]
      exact congrArg graphVertex (Subsingleton.elim e.right default)
    · right
      have hp : 0 < t := lt_of_le_of_ne (unitInterval.nonneg t) (Ne.symm ht0)
      have hq : t < 1 := lt_of_le_of_ne (unitInterval.le_one t) ht1
      refine ⟨⟨edgeIndexEquiv S e,⟨t,hp,hq⟩⟩,?_⟩
      dsimp only [bouquetAllInteriors,ContinuousMap.coe_mk,edgeInterior]
      change graphEdgePath ((edgeIndexEquiv S).symm (edgeIndexEquiv S e)) t = _
      rw [(edgeIndexEquiv S).symm_apply_apply]
      rfl

theorem bouquet_base_interior_separated (p : Σ _ : S, Ioo (0 : I) 1) :
    Separated (base S) (bouquetAllInteriors S p) := by
  apply separated_continuous (bouquetHeight S)
  dsimp only [bouquetHeight,ContinuousMap.coe_mk,bouquetAllInteriors,edgeInterior,
    base,graphVertex,graphEdgePath,graphRealizationQuotient,Quotient.lift_mk,rawBouquetHeight]
  change (0 : ℝ) ≠ min p.2.val.val (1-p.2.val.val)
  apply ne_of_lt
  apply lt_min
  · exact p.2.property.1
  · have h := p.2.property.2
    change p.2.val.val < 1 at h
    linarith

/-- The genuine weak endpoint quotient is Hausdorff for arbitrary generator types. -/
instance bouquet_t2Space : T2Space (Bouquet S) where
  t2 x y hxy := by
    rcases bouquet_point_cases S x with rfl | ⟨p,rfl⟩
    · rcases bouquet_point_cases S y with rfl | ⟨q,rfl⟩
      · exact (hxy rfl).elim
      · exact bouquet_base_interior_separated S q
    · rcases bouquet_point_cases S y with rfl | ⟨q,rfl⟩
      · exact (bouquet_base_interior_separated S p).symm
      · exact separated_openEmbedding _ (bouquetAllInteriors_isOpenEmbedding S)
          (fun h => hxy (congrArg (bouquetAllInteriors S) h))
end Bouquet

section Attachment
variable {X : Type u} [TopologicalSpace X] {R : Type v}

def rawDiskRadius : CellAttachment.Raw X R → ℝ
  | Sum.inl _ => 1
  | Sum.inr p => ‖p.2.val‖

/-- The actual quotient disk radius, equal to one on the whole old base. -/
def attachmentRadius (f : R → C(Circle,X)) : C(CellAttachment.Space f,ℝ) where
  toFun := Quot.lift (rawDiskRadius (X := X) (R := R)) (by
    intro a b h
    cases h with
    | boundary i z => exact Circle.norm_coe z)
  continuous_toFun := by
    apply continuous_quot_lift
    have hc : Continuous (Sum.elim (fun _ : X => (1 : ℝ))
        (fun p : Σ _ : R, CellAttachment.Disk => ‖p.2.val‖)) := by
      apply Continuous.sumElim
      · exact continuous_const
      · apply continuous_sigma
        intro i
        exact continuous_subtype_val.norm
    exact hc.congr (fun z => by cases z <;> rfl)

theorem attachment_point_cases (f : R → C(Circle,X)) (z : CellAttachment.Space f) :
    (∃ x, CellAttachment.inclusion f x = z) ∨
      ∃ p : Σ _ : R, CellAttachment.OpenDisk, CellAttachment.interiorMap f p = z := by
  obtain ⟨a,rfl⟩ := (CellAttachment.quotientMap_isQuotientMap f).surjective z
  cases a with
  | inl x => exact Or.inl ⟨x,rfl⟩
  | inr p =>
    rcases p with ⟨i,z⟩
    by_cases hz : ‖z.val‖ = 1
    · exact Or.inl ⟨f i (CellAttachment.diskBoundaryPoint z hz),
        (CellAttachment.characteristic_boundary f i (CellAttachment.diskBoundaryPoint z hz)).symm⟩
    · have hz' : ‖z.val‖ < 1 := lt_of_le_of_ne z.property hz
      exact Or.inr ⟨⟨i,⟨z.val,hz'⟩⟩,rfl⟩

theorem attachment_old_points_separated [T2Space X]
    (f : R → C(Circle,X)) (x₀ x y : X) (hxy : x ≠ y) :
    Separated (CellAttachment.inclusion f x) (CellAttachment.inclusion f y) := by
  let r := CellAttachment.neighborhoodRetraction f x₀
  rcases t2_separation hxy with ⟨A,B,hA,hB,hx,hy,hd⟩
  have ho := (CellAttachment.puncturedNeighborhood_isOpen f).isOpenMap_subtype_val
  refine ⟨Subtype.val '' (r ⁻¹' A),Subtype.val '' (r ⁻¹' B),
    ho _ (hA.preimage r.continuous),ho _ (hB.preimage r.continuous),
    ⟨CellAttachment.neighborhoodInclusion f x,hx,rfl⟩,
    ⟨CellAttachment.neighborhoodInclusion f y,hy,rfl⟩,?_⟩
  apply disjoint_left.mpr
  rintro z ⟨a,ha,he⟩ ⟨b,hb,he'⟩
  have hab : a = b := Subtype.ext (he.trans he'.symm)
  subst b
  exact disjoint_left.mp hd ha hb

theorem attachment_old_interior_separated (f : R → C(Circle,X))
    (x : X) (p : Σ _ : R, CellAttachment.OpenDisk) :
    Separated (CellAttachment.inclusion f x) (CellAttachment.interiorMap f p) := by
  apply separated_continuous (attachmentRadius f)
  change (1 : ℝ) ≠ ‖p.2.val‖
  exact ne_of_gt p.2.property

/-- Genuine disk adjunctions preserve Hausdorffness, with no finite/countable restriction. -/
theorem attachment_t2Space [T2Space X] (f : R → C(Circle,X)) (x₀ : X) :
    T2Space (CellAttachment.Space f) := by
  constructor
  intro z w hzw
  rcases attachment_point_cases f z with ⟨x,rfl⟩ | ⟨p,rfl⟩
  · rcases attachment_point_cases f w with ⟨y,rfl⟩ | ⟨q,rfl⟩
    · exact attachment_old_points_separated f x₀ x y
        (fun h => hzw (congrArg (CellAttachment.inclusion f) h))
    · exact attachment_old_interior_separated f x q
  · rcases attachment_point_cases f w with ⟨y,rfl⟩ | ⟨q,rfl⟩
    · exact (attachment_old_interior_separated f y p).symm
    · exact separated_openEmbedding _ (CellAttachment.interiorMap_isOpenEmbedding f)
        (fun h => hzw (congrArg (CellAttachment.interiorMap f) h))
end Attachment

end PresentationComplex
end
end Standalone_PresentationComplex_Hausdorff

/-! Source module: PresentationComplex.Main -/
section Standalone_PresentationComplex_Main



/-! Arbitrary presentation complexes and genuine Hausdorff CW realization of every group. -/
noncomputable section
universe u v
namespace PresentationComplex
variable {S : Type u} {R : Type v}

instance presentation_t2Space (r : R → FreeGroup S) : T2Space (Space r) :=
  attachment_t2Space (relatorMap r) (base S)

/-- The full independently scoped target, with actual topology and literal compatibility. -/
def completeStatement : Prop :=
  ∀ {S : Type u} {R : Type v} (r : R → FreeGroup S),
    ∃ (cw : Topology.CWComplex (Set.univ : Set (Space r)))
      (b : FundamentalGroup (Bouquet S) (base S) ≃* FreeGroup S)
      (e : FundamentalGroup (Space r) (point r) ≃*
        (FreeGroup S ⧸ relatorNormalClosure r)),
      T2Space (Space r) ∧ PathConnectedSpace (Space r) ∧
      Nonempty (cw.cell 0 ≃ PUnit.{max u v + 1}) ∧
      Nonempty (cw.cell 1 ≃ S) ∧ Nonempty (cw.cell 2 ≃ R) ∧
      (∀ n, 2 < n → IsEmpty (cw.cell n)) ∧
      (∀ s, b (Path.Homotopic.Quotient.mk (edgeLoop s)) = FreeGroup.of s) ∧
      e.toMonoidHom.comp (CellAttachment.inclusionPi1 (relatorMap r) (base S)) =
        (QuotientGroup.mk' (relatorNormalClosure r)).comp b.toMonoidHom ∧
      (∀ s, e (Path.Homotopic.Quotient.mk ((edgeLoop s).map (inclusion r).continuous)) =
        QuotientGroup.mk' (relatorNormalClosure r) (FreeGroup.of s))

/-- Every arbitrary presentation has the genuine connected Hausdorff CW complex
of dimension at most two, with exact ordinary fundamental group and generators. -/
theorem presentation_complex : completeStatement.{u,v} := by
  intro S R r
  exact ⟨presentationCW r,bouquetEquiv S,presentationPi1Equiv r,
    inferInstance,inferInstance,⟨Equiv.refl _⟩,
    ⟨presentationCW_generatorCells r⟩,⟨presentationCW_relatorCells r⟩,
    presentationCW_noHigherCells r,
    bouquetEquiv_edgeLoop,presentationPi1Equiv_inclusion r,presentationPi1Equiv_generator r⟩

/-- Every group is the fundamental group of this genuine presentation space. -/
def everyGroupPi1Equiv (G : Type u) [Group G] :
    FundamentalGroup (EveryGroupSpace G) (everyGroupPoint G) ≃* G :=
  (presentationPi1Equiv (groupRelators G)).trans (groupPresentationEquiv G)

/-- The generator indexed by g is the actual interval loop and is labeled exactly g. -/
theorem everyGroupPi1Equiv_generator (G : Type u) [Group G] (g : G) :
    everyGroupPi1Equiv G (Path.Homotopic.Quotient.mk
      ((edgeLoop g).map (inclusion (groupRelators G)).continuous)) = g := by
  change groupPresentationEquiv G (presentationPi1Equiv (groupRelators G)
    (Path.Homotopic.Quotient.mk ((edgeLoop g).map (inclusion (groupRelators G)).continuous))) = g
  rw [presentationPi1Equiv_generator]
  exact groupPresentationEquiv_generator G g

/-- The identity relator supplies a genuine indexed open two-cell for every group. -/
theorem everyGroupCW_hasTwoCell (G : Type u) [Group G] :
    Nonempty ((presentationCW (groupRelators G)).cell 2) :=
  ⟨(presentationCW_relatorCells (groupRelators G)).symm (Sum.inr PUnit.unit)⟩

/-- The headline realization theorem has no CW, free-group, kernel, finiteness,
countability, or generator-identification oracle among its inputs. -/
theorem every_group_fundamental_group (G : Type u) [Group G] :
    ∃ cw : Topology.CWComplex (Set.univ : Set (EveryGroupSpace G)),
      T2Space (EveryGroupSpace G) ∧ PathConnectedSpace (EveryGroupSpace G) ∧
      (∀ n, 2 < n → IsEmpty (cw.cell n)) ∧ Nonempty (cw.cell 2) ∧
      Nonempty (FundamentalGroup (EveryGroupSpace G) (everyGroupPoint G) ≃* G) :=
  ⟨presentationCW (groupRelators G),inferInstance,inferInstance,
    presentationCW_noHigherCells (groupRelators G),everyGroupCW_hasTwoCell G,
    ⟨everyGroupPi1Equiv G⟩⟩

end PresentationComplex
end
end Standalone_PresentationComplex_Main
