#!/usr/bin/env python3
"""Flatten frozen source reproducibly, keeping Challenge independent of its proof.

No Lean process is started. --check compares generated bytes without writing.
The Challenge contains the full construction closure of Relators and the exact
completeStatement declaration copied from Main, but none of Main's proofs.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
SOLUTION_ROOT = 'PresentationComplex.Main'
CHALLENGE_ROOT = 'PresentationComplex.Relators'
LOCAL_PREFIXES = ('PresentationComplex', 'FiniteGraphFreeGroup', 'CellAttachment', 'ClassicalSVK', 'Lean4')
IMPORT_RE = re.compile(r'^\s*(?:public\s+)?import\s+(.+?)\s*$', re.M)
HEADER = '''/-
Arbitrary presentation complexes and the genuine Hausdorff CW realization of every group.
Mathematical source: Allen Hatcher, Algebraic Topology, Corollary 1.28.
Authors: Arthur Freitas Ramos, David Barros Hulak,
Ruy Jose Guerra Barretto de Queiroz.
First-party source: Apache-2.0. Reused source notices are retained below.
Generated by scripts/generate_standalone.py; edit the modular sources instead.
-/
'''


def sha256(data: str | bytes) -> str:
    if isinstance(data, str):
        data = data.encode('utf-8')
    return hashlib.sha256(data).hexdigest()


def code_only(source: str) -> str:
    """Mask nested Lean comments and strings, retaining offsets and newlines."""
    out = list(source)
    i = 0
    depth = 0
    quoted = False
    while i < len(source):
        if depth:
            if source.startswith('/-', i):
                out[i:i+2] = '  '; depth += 1; i += 2
            elif source.startswith('-/', i):
                out[i:i+2] = '  '; depth -= 1; i += 2
            else:
                if source[i] != '\n': out[i] = ' '
                i += 1
        elif quoted:
            if source[i] == '\\' and i + 1 < len(source):
                out[i:i+2] = '  '; i += 2
            else:
                if source[i] == '"': quoted = False
                if source[i] != '\n': out[i] = ' '
                i += 1
        elif source.startswith('/-', i):
            out[i:i+2] = '  '; depth = 1; i += 2
        elif source.startswith('--', i):
            while i < len(source) and source[i] != '\n':
                out[i] = ' '; i += 1
        elif source[i] == '"':
            out[i] = ' '; quoted = True; i += 1
        else:
            i += 1
    if depth or quoted:
        raise ValueError('unterminated Lean comment or string')
    return ''.join(out)


def imports(source: str) -> list[str]:
    return [name for line in IMPORT_RE.findall(code_only(source)) for name in line.split()]


def source_path(name: str) -> Path | None:
    p = ROOT.joinpath(*name.split('.')).with_suffix('.lean')
    return p if p.is_file() else None


def closure(roots: list[str]) -> tuple[list[tuple[str, Path]], list[str]]:
    seen: set[str] = set()
    active: set[str] = set()
    order: list[tuple[str, Path]] = []
    external: list[str] = []

    def visit(name: str) -> None:
        if name in active:
            raise ValueError(f'cyclic local imports through {name}')
        if name in seen: return
        path = source_path(name)
        if path is None:
            if name.split('.')[0] in LOCAL_PREFIXES:
                raise ValueError(f'missing local source for {name}')
            seen.add(name); external.append(name); return
        active.add(name)
        for dep in imports(path.read_text(encoding='utf-8')): visit(dep)
        active.remove(name); seen.add(name); order.append((name, path))

    for name in roots: visit(name)
    return order, external


def body(source: str) -> str:
    lines = source.splitlines(keepends=True)
    clean = code_only(source).splitlines(keepends=True)
    output = []
    for original, line in zip(lines, clean):
        if re.match(r'^\s*(?:public\s+)?import\s+', line): continue
        if line.strip() == 'module': continue
        if line.strip() == '@[expose] public section': continue
        output.append(original)
    result = ''.join(output)
    return result if result.endswith('\n') else result + '\n'


def wrap(name: str, source: str) -> tuple[str, int]:
    """Emulate module EOF scope closure without changing declaration namespaces."""
    content = body(source)
    scopes: list[tuple[str, str]] = []
    for number, line in enumerate(code_only(content).splitlines(), 1):
        opening = re.match(r'^\s*(?:(?:noncomputable|public)\s+)?(section|namespace)(?:\s+(\S+))?\s*$', line)
        if opening:
            kind, label = opening.groups()
            scopes.append((kind, label or ''))
            continue
        closing = re.match(r'^\s*end(?:\s+(\S+))?\s*$', line)
        if closing:
            label = closing.group(1)
            if not scopes: raise ValueError(f'{name}:{number}: unmatched end')
            if label is None or scopes[-1][1] == label:
                scopes.pop(); continue
            # Lean accepts a dotted end closing several nested namespaces.
            names = []
            matched = False
            for n in range(len(scopes)-1, -1, -1):
                if scopes[n][0] != 'namespace': break
                names.insert(0, scopes[n][1])
                if '.'.join(names) == label:
                    del scopes[n:]; matched = True; break
            if not matched:
                raise ValueError(f'{name}:{number}: end {label} mismatches {scopes[-1]}')
    label = 'Standalone_' + name.replace('.', '_')
    result = (f'\n/-! Source module: {name} -/\nsection {label}\n' + content +
              'end\n' * len(scopes) + f'end {label}\n')
    return result, len(scopes)


def statement_source() -> str:
    """Copy precisely the existing declaration, with no proof or instance."""
    source = (ROOT / 'PresentationComplex/Main.lean').read_text(encoding='utf-8')
    clean = code_only(source)
    starts = list(re.finditer(r'^def completeStatement\s*:\s*Prop\s*:=', clean, re.M))
    if len(starts) != 1:
        raise ValueError('Main must contain exactly one completeStatement declaration')
    start = starts[0].start()
    following = re.search(r'^(?:theorem|def|abbrev|instance|end)\b', clean[starts[0].end():], re.M)
    if following is None: raise ValueError('cannot find end of completeStatement')
    end = starts[0].end() + following.start()
    # Strip only trailing whitespace and the next declaration's documentation.
    region = source[start:end]
    next_doc = region.rfind('/--')
    if next_doc >= 0: region = region[:next_doc]
    declaration = region.rstrip() + '\n'
    expected = ('{S : Type u}', '{R : Type v}', 'Topology.CWComplex',
                'T2Space (Space r)', 'PathConnectedSpace (Space r)',
                '2 < n', 'edgeLoop s', 'CellAttachment.inclusionPi1',
                'relatorNormalClosure r', 'inclusion r')
    for term in expected:
        if term not in declaration: raise ValueError(f'full target lost required component: {term}')
    if re.search(r'\b(?:sorry|admit|axiom)\b', code_only(declaration)):
        raise ValueError('statement contains an admission')
    return ('/-! Exact completeStatement declaration from PresentationComplex.Main; no proof imported. -/\n'
            'noncomputable section\nuniverse u v\nnamespace PresentationComplex\n' +
            declaration + '\nend PresentationComplex\nend\n')


def prefix(external: list[str]) -> str:
    apache = (ROOT / 'LICENSE').read_text(encoding='utf-8')
    mit = (ROOT / 'Lean4/LICENSE.md').read_text(encoding='utf-8')
    notices = '/-\nApache-2.0 license for first-party and Apache-licensed reused sources.\n' + apache + '\n-/\n'
    notices += '/-\nVendored directed-topology helpers retain this MIT notice.\n' + mit + '\n-/\n'
    return HEADER + notices + 'module\n\n' + '\n'.join('public import ' + n for n in external) + '\n\n@[expose] public section\n'


def render(order: list[tuple[str, Path]], external: list[str]) -> tuple[str, list[dict]]:
    output = prefix(external)
    manifest = []
    for name, path in order:
        source = path.read_text(encoding='utf-8')
        if re.search(r'\b(?:sorry|admit|axiom)\b', code_only(source)):
            raise ValueError(f'proof source contains an admission or custom axiom: {name}')
        wrapped, closures = wrap(name, source)
        output += wrapped
        manifest.append({'module': name, 'path': str(path.relative_to(ROOT)),
                         'source_sha256': sha256(source), 'eof_scopes_closed': closures})
    return output, manifest


def generate() -> dict[str, str]:
    solution_order, solution_external = closure([SOLUTION_ROOT])
    challenge_order, challenge_external = closure([CHALLENGE_ROOT])
    banned = {'PresentationComplex.Main', 'PresentationComplex.FundamentalGroup',
              'PresentationComplex.CW', 'PresentationComplex.Hausdorff', 'CellAttachment.Main'}
    overlap = banned.intersection(name for name, _ in challenge_order)
    if overlap: raise ValueError(f'Challenge imports proven target machinery: {sorted(overlap)}')
    cw_import = 'Mathlib.Topology.CWComplex.Classical.Basic'
    if cw_import not in challenge_external: challenge_external.append(cw_import)
    solution, solution_manifest = render(solution_order, solution_external)
    challenge, challenge_manifest = render(challenge_order, challenge_external)
    statement = statement_source()
    challenge += '\n' + statement + '''
namespace PresentationComplex
universe u v
/-- Independent full arbitrary-presentation challenge. The following is its sole intentional hole. -/
theorem presentation_complex : completeStatement.{u,v} := by
  sorry
end PresentationComplex
'''
    if len(re.findall(r'\bsorry\b', code_only(challenge))) != 1:
        raise ValueError('Challenge must have exactly one intentional sorry')
    if re.search(r'\b(?:sorry|admit|axiom)\b', code_only(solution)):
        raise ValueError('Solution must be entirely free of admissions and custom axioms')
    for name, content in [('Solution', solution), ('Challenge', challenge)]:
        if any(n.split('.')[0] in LOCAL_PREFIXES or n == 'Solution' for n in imports(content)):
            raise ValueError(f'{name} is not standalone')
    if 'every_group_fundamental_group' not in code_only(solution):
        raise ValueError('Solution lost the every-group consequence')
    metadata = {
        'status': 'generated; compilation and kernel verification not asserted',
        'generator': 'scripts/generate_standalone.py',
        'solution_root': SOLUTION_ROOT, 'challenge_construction_root': CHALLENGE_ROOT,
        'statement_source': 'PresentationComplex/Main.lean:completeStatement',
        'statement_sha256': sha256(statement),
        'solution_sha256': sha256(solution), 'challenge_sha256': sha256(challenge),
        'solution_local_modules': solution_manifest, 'challenge_local_modules': challenge_manifest,
        'solution_external_imports': solution_external, 'challenge_external_imports': challenge_external,
        'challenge_intentional_holes': ['PresentationComplex.presentation_complex'],
        'source_transform': 'Remove import/module/expose-section commands; isolate module scopes in sections and close EOF scopes. All other source text and notices are retained.',
    }
    return {'Solution.lean': solution, 'Challenge.lean': challenge,
            'reports/standalone-manifest.json': json.dumps(metadata, indent=2) + '\n',
            'reports/standalone-manifest.txt': ''.join(f'{n} {p.relative_to(ROOT)}\n' for n, p in solution_order)}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if checked-in outputs differ; do not write')
    args = parser.parse_args()
    generated = generate()
    for relative, content in generated.items():
        path = ROOT / relative
        if args.check:
            if not path.is_file() or path.read_text(encoding='utf-8') != content:
                raise SystemExit(f'STALE: {relative}; rerun scripts/generate_standalone.py')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
    manifest = json.loads(generated['reports/standalone-manifest.json'])
    print(f"{'CHECKED' if args.check else 'GENERATED'}: Solution {len(manifest['solution_local_modules'])} local modules, "
          f"Challenge {len(manifest['challenge_local_modules'])} construction modules, one intentional theorem hole")


if __name__ == '__main__': main()
