#!/usr/bin/env python3
"""Flatten frozen source reproducibly, keeping Challenge independent of its proof.

No Lean process is started. --check compares generated bytes without writing.
The Challenge contains only the every-group construction closure and both exact
headline statements copied from Main, but none of Main's proofs.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
SOLUTION_ROOT = 'PresentationComplex.Main'
CHALLENGE_ROOT = 'PresentationComplex.EveryGroupConstruction'
LOCAL_PREFIXES = ('PresentationComplex', 'FiniteGraphFreeGroup', 'CellAttachment', 'ClassicalSVK', 'Lean4', 'PresentationPackage')
IMPORT_RE = re.compile(r'^\s*(?:public\s+)?import\s+(.+?)\s*$', re.M)
HEADER = '''/-
Arbitrary presentation complexes and the genuine Hausdorff CW realization of every group.
Mathematical source: Allen Hatcher, Algebraic Topology, Corollary 1.28.
Authors: Arthur Freitas Ramos, David Barros Hulak,
Ruy Jose Guerra Barretto de Queiroz.
First-party source: Apache-2.0. Reused source notices are retained below.
Generated by scripts/generate_standalone.py; edit the modular sources instead.
-/
'''


def sha256(data: str | bytes) -> str:
    if isinstance(data, str):
        data = data.encode('utf-8')
    return hashlib.sha256(data).hexdigest()


def code_only(source: str) -> str:
    """Mask nested Lean comments and strings, retaining offsets and newlines."""
    out = list(source)
    i = 0
    depth = 0
    quoted = False
    while i < len(source):
        if depth:
            if source.startswith('/-', i):
                out[i:i+2] = '  '; depth += 1; i += 2
            elif source.startswith('-/', i):
                out[i:i+2] = '  '; depth -= 1; i += 2
            else:
                if source[i] != '\n': out[i] = ' '
                i += 1
        elif quoted:
            if source[i] == '\\' and i + 1 < len(source):
                out[i:i+2] = '  '; i += 2
            else:
                if source[i] == '"': quoted = False
                if source[i] != '\n': out[i] = ' '
                i += 1
        elif source.startswith('/-', i):
            out[i:i+2] = '  '; depth = 1; i += 2
        elif source.startswith('--', i):
            while i < len(source) and source[i] != '\n':
                out[i] = ' '; i += 1
        elif source[i] == '"':
            out[i] = ' '; quoted = True; i += 1
        else:
            i += 1
    if depth or quoted:
        raise ValueError('unterminated Lean comment or string')
    return ''.join(out)


def imports(source: str) -> list[str]:
    return [name for line in IMPORT_RE.findall(code_only(source)) for name in line.split()]


def source_path(name: str) -> Path | None:
    p = ROOT.joinpath(*name.split('.')).with_suffix('.lean')
    return p if p.is_file() else None


def closure(roots: list[str]) -> tuple[list[tuple[str, Path]], list[str]]:
    seen: set[str] = set()
    active: set[str] = set()
    order: list[tuple[str, Path]] = []
    external: list[str] = []

    def visit(name: str) -> None:
        if name in active:
            raise ValueError(f'cyclic local imports through {name}')
        if name in seen: return
        path = source_path(name)
        if path is None:
            if name.split('.')[0] in LOCAL_PREFIXES:
                raise ValueError(f'missing local source for {name}')
            seen.add(name); external.append(name); return
        active.add(name)
        for dep in imports(path.read_text(encoding='utf-8')): visit(dep)
        active.remove(name); seen.add(name); order.append((name, path))

    for name in roots: visit(name)
    return order, external


def body(source: str) -> str:
    lines = source.splitlines(keepends=True)
    clean = code_only(source).splitlines(keepends=True)
    output = []
    for original, line in zip(lines, clean):
        if re.match(r'^\s*(?:public\s+)?import\s+', line): continue
        if line.strip() == 'module': continue
        if line.strip() == '@[expose] public section': continue
        output.append(original)
    result = ''.join(output)
    # Private names contain the generated module name. Stable helper names are
    # essential to exact Challenge/Solution body comparison. Visibility alone
    # is changed; all declaration bodies and references remain intact.
    result = re.sub(r'^(\s*)private\s+(?=(?:def|theorem|lemma|abbrev|instance|opaque)\b)', r'\1', result, flags=re.M)
    return result if result.endswith('\n') else result + '\n'


def wrap(name: str, source: str) -> tuple[str, int]:
    """Emulate module EOF scope closure without changing declaration namespaces."""
    content = body(source)
    scopes: list[tuple[str, str]] = []
    for number, line in enumerate(code_only(content).splitlines(), 1):
        opening = re.match(r'^\s*(?:(?:noncomputable|public)\s+)?(section|namespace)(?:\s+(\S+))?\s*$', line)
        if opening:
            kind, label = opening.groups()
            scopes.append((kind, label or ''))
            continue
        closing = re.match(r'^\s*end(?:\s+(\S+))?\s*$', line)
        if closing:
            label = closing.group(1)
            if not scopes: raise ValueError(f'{name}:{number}: unmatched end')
            if label is None or scopes[-1][1] == label:
                scopes.pop(); continue
            # Lean accepts a dotted end closing several nested namespaces.
            names = []
            matched = False
            for n in range(len(scopes)-1, -1, -1):
                if scopes[n][0] != 'namespace': break
                names.insert(0, scopes[n][1])
                if '.'.join(names) == label:
                    del scopes[n:]; matched = True; break
            if not matched:
                raise ValueError(f'{name}:{number}: end {label} mismatches {scopes[-1]}')
    label = 'Standalone_' + name.replace('.', '_')
    result = (f'\n/-! Source module: {name} -/\nsection {label}\n' + content +
              'end\n' * len(scopes) + f'end {label}\n')
    return result, len(scopes)


def statement_source() -> str:
    """Copy precisely the existing declaration, with no proof or instance."""
    source = (ROOT / 'PresentationComplex/Main.lean').read_text(encoding='utf-8')
    clean = code_only(source)
    starts = list(re.finditer(r'^def completeStatement\s*:\s*Prop\s*:=', clean, re.M))
    if len(starts) != 1:
        raise ValueError('Main must contain exactly one completeStatement declaration')
    start = starts[0].start()
    following = re.search(r'^(?:theorem|def|abbrev|instance|end)\b', clean[starts[0].end():], re.M)
    if following is None: raise ValueError('cannot find end of completeStatement')
    end = starts[0].end() + following.start()
    # Strip only trailing whitespace and the next declaration's documentation.
    region = source[start:end]
    next_doc = region.rfind('/--')
    if next_doc >= 0: region = region[:next_doc]
    declaration = region.rstrip() + '\n'
    expected = ('{S : Type u}', '{R : Type v}', 'Topology.CWComplex',
                'T2Space (Space r)', 'PathConnectedSpace (Space r)',
                '2 < n', 'edgeLoop s', 'CellAttachment.inclusionPi1',
                'relatorNormalClosure r', 'inclusion r',
                'cw.cell 0 ≃ PUnit', 'cw.cell 1 ≃ S', 'cw.cell 2 ≃ R')
    for term in expected:
        if term not in declaration: raise ValueError(f'full target lost required component: {term}')
    if re.search(r'\b(?:sorry|admit|axiom)\b', code_only(declaration)):
        raise ValueError('statement contains an admission')
    return ('/-! Exact completeStatement declaration from PresentationComplex.Main; no proof imported. -/\n'
            'noncomputable section\nuniverse u v\nnamespace PresentationComplex\n' +
            declaration + '\nend PresentationComplex\nend\n')


def every_group_target() -> str:
    """Copy the exact second headline type, never its completed proof."""
    source = (ROOT / 'PresentationComplex/Main.lean').read_text(encoding='utf-8')
    start = source.index('theorem every_group_fundamental_group ')
    end = source.index(':=', start)
    target = source[start:end]
    for required in ['Topology.CWComplex', 'T2Space', 'PathConnectedSpace',
                     'IsEmpty (cw.cell n)', 'Nonempty (cw.cell 2)', '≃* G']:
        if required not in target: raise ValueError(f'every-group target lost {required}')
    return target + ':= by\n  sorry\n'


def prefix(external: list[str]) -> str:
    apache = (ROOT / 'LICENSE').read_text(encoding='utf-8')
    mit = (ROOT / 'Lean4/LICENSE.md').read_text(encoding='utf-8')
    notices = '/-\nApache-2.0 license for first-party and Apache-licensed reused sources.\n' + apache + '\n-/\n'
    notices += '/-\nVendored directed-topology helpers retain this MIT notice.\n' + mit + '\n-/\n'
    return HEADER + notices + 'module\n\n' + '\n'.join('public import ' + n for n in external) + '\n\n@[expose] public section\n'


def render(order: list[tuple[str, Path]], external: list[str]) -> tuple[str, list[dict]]:
    output = prefix(external)
    manifest = []
    for name, path in order:
        source = path.read_text(encoding='utf-8')
        if re.search(r'\b(?:sorry|admit|axiom)\b', code_only(source)):
            raise ValueError(f'proof source contains an admission or custom axiom: {name}')
        wrapped, closures = wrap(name, source)
        output += wrapped
        manifest.append({'module': name, 'path': path.relative_to(ROOT).as_posix(),
                         'source_sha256': sha256(source), 'eof_scopes_closed': closures,
                         'private_modifiers_removed': len(re.findall(r'^\s*private\s+(?:def|theorem|lemma|abbrev|instance|opaque)\b', code_only(source), re.M))})
    return output, manifest


def generate() -> dict[str, str]:
    solution_order, solution_external = closure([SOLUTION_ROOT])
    challenge_order, challenge_external = closure([CHALLENGE_ROOT])
    banned = {'PresentationComplex.Main', 'PresentationComplex.FundamentalGroup',
              'PresentationComplex.CW', 'PresentationComplex.Hausdorff',
              'PresentationComplex.EveryGroupPresentation', 'CellAttachment.Main'}
    overlap = banned.intersection(name for name, _ in challenge_order)
    if overlap: raise ValueError(f'Challenge imports proven target machinery: {sorted(overlap)}')
    minimal_challenge_external = list(challenge_external)
    cw_import = 'Mathlib.Topology.CWComplex.Classical.Basic'
    if cw_import not in solution_external: solution_external.append(cw_import)
    # Identical imported environments and a common construction prefix prevent
    # later proof imports, simp lemmas, or instances from changing common terms.
    challenge_external = list(solution_external)
    construction_names = {name for name, _ in challenge_order}
    solution_order = challenge_order + [(name, path) for name, path in solution_order if name not in construction_names]
    # Render one identical construction prefix for both environments. Challenge
    # must inline it: canonical intake deliberately excludes repository oleans.
    # Solution may import the bounded construction/proof modules.
    construction, challenge_manifest = render(challenge_order, challenge_external)
    proof_order = [(name, path) for name, path in solution_order if name not in construction_names]
    generated_modules = {'PresentationPackage/Construction.lean': construction}
    _, solution_manifest = render(solution_order, solution_external)
    previous = 'PresentationPackage.Construction'
    chunk = prefix([previous])
    chunk_modules = []
    chunks = []
    # Split only at original module boundaries, keeping EOF scope closure intact.
    # 8,000 leaves headroom below the conservatively enforced user-provided cap.
    for name, path in proof_order:
        wrapped, _ = wrap(name, path.read_text(encoding='utf-8'))
        if len((chunk + wrapped).splitlines()) > 8000 and chunk_modules:
            module = f'PresentationPackage.Proof{len(chunks) + 1}'
            generated_modules[module.replace('.', '/') + '.lean'] = chunk
            chunks.append({'module': module, 'source_modules': chunk_modules})
            previous = module
            chunk = prefix([previous]); chunk_modules = []
        chunk += wrapped; chunk_modules.append(name)
    if chunk_modules:
        module = f'PresentationPackage.Proof{len(chunks) + 1}'
        generated_modules[module.replace('.', '/') + '.lean'] = chunk
        chunks.append({'module': module, 'source_modules': chunk_modules})
        previous = module
    solution = prefix([previous])
    challenge = construction
    statement = statement_source()
    challenge += '\n' + statement + '''
namespace PresentationComplex
universe u v
/-- Independent full arbitrary-presentation challenge. -/
theorem presentation_complex : completeStatement.{u,v} := by
  sorry
''' + every_group_target() + 'end PresentationComplex\n'
    if len(re.findall(r'\bsorry\b', code_only(challenge))) != 2:
        raise ValueError('Challenge must have exactly two intentional theorem holes')
    if re.search(r'\b(?:sorry|admit|axiom)\b', code_only(solution)):
        raise ValueError('Solution must be entirely free of admissions and custom axioms')
    if any(n.startswith('PresentationPackage.Proof') or n == 'Solution'
           for n in imports(challenge) + imports(construction)):
        raise ValueError('Challenge construction imports Solution proof machinery')
    if 'every_group_fundamental_group' not in code_only(''.join(generated_modules.values())):
        raise ValueError('Solution lost the every-group consequence')
    for name, content in {**generated_modules, 'Challenge.lean': challenge, 'Solution.lean': solution}.items():
        if len(content.splitlines()) > 10000:
            raise ValueError(f'{name} exceeds the conservative 10,000-line cap')
    if len(challenge.encode('utf-8')) > 102400:
        raise ValueError('Challenge exceeds the user-reported canonical 100 KiB byte cap')
    metadata = {
        'challenge_byte_cap': {'maximum': 102400, 'actual': len(challenge.encode('utf-8')), 'basis': 'user-reported actual canonical intake gate'},
        'generated_modules': {name: {'sha256': sha256(content), 'lines': len(content.splitlines())} for name, content in generated_modules.items()},
        'proof_chunks': chunks,
        'line_cap': {'maximum': 10000, 'basis': 'user-provided intake constraint; official current policy not independently verified'},
        'status': 'generated; compilation and kernel verification not asserted',
        'generator': 'scripts/generate_standalone.py',
        'solution_root': SOLUTION_ROOT, 'challenge_construction_root': CHALLENGE_ROOT,
        'statement_source': 'PresentationComplex/Main.lean:completeStatement',
        'statement_sha256': sha256(statement),
        'solution_sha256': sha256(solution), 'challenge_sha256': sha256(challenge),
        'solution_local_modules': solution_manifest, 'challenge_local_modules': challenge_manifest,
        'solution_external_imports': solution_external, 'challenge_external_imports': challenge_external,
        'challenge_minimal_construction_imports': minimal_challenge_external,
        'shared_construction_prefix': [name for name, _ in challenge_order],
        'shared_environment_note': 'Challenge inlines the exact generated Construction source, with only pinned external imports; Solution imports that same source as a module. Stable public helper names and identical declaration order preserve common construction bodies across module names. Proof chunks preserve original module/declaration order.',
        'challenge_intentional_holes': ['PresentationComplex.presentation_complex',
                                        'PresentationComplex.every_group_fundamental_group'],
        'source_transform': 'Remove import/module/expose-section commands; isolate module scopes in sections and close EOF scopes; remove private visibility modifiers for stable helper names across Challenge/Solution. All declaration bodies and source notices are retained.',
    }
    return {**generated_modules, 'Solution.lean': solution, 'Challenge.lean': challenge,
            'reports/standalone-manifest.json': json.dumps(metadata, indent=2) + '\n',
            'reports/standalone-manifest.txt': ''.join(f'{n} {p.relative_to(ROOT).as_posix()}\n' for n, p in solution_order)}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if checked-in outputs differ; do not write')
    args = parser.parse_args()
    generated = generate()
    expected = {ROOT/name for name in generated if name.startswith('PresentationPackage/')}
    extras = set((ROOT/'PresentationPackage').glob('*.lean')) - expected
    if extras:
        raise SystemExit('Unexpected generated modules; review and remove explicitly: ' + ', '.join(str(p.relative_to(ROOT)) for p in sorted(extras)))
    for relative, content in generated.items():
        path = ROOT / relative
        if args.check:
            if not path.is_file() or path.read_bytes() != content.encode('utf-8'):
                raise SystemExit(f'STALE: {relative}; rerun scripts/generate_standalone.py')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
    manifest = json.loads(generated['reports/standalone-manifest.json'])
    print(f"{'CHECKED' if args.check else 'GENERATED'}: Solution {len(manifest['solution_local_modules'])} local modules, "
          f"Challenge {len(manifest['challenge_local_modules'])} construction modules, two intentional theorem holes")


if __name__ == '__main__': main()
