module

public import Mathlib.Analysis.Complex.Circle
public import Mathlib.Topology.Constructions
public import Mathlib.AlgebraicTopology.FundamentalGroupoid.FundamentalGroup

@[expose] public section


/-!
# Genuine adjunction space for an arbitrary family of two-cells

The carrier is the quotient of the topological disjoint union of the original
space and the indexed closed complex unit disks. The relation is generated by
exactly the prescribed boundary identifications; the topology is the quotient
topology. No separation or finiteness assumptions are used.
-/

noncomputable section

namespace CellAttachment

universe u v

/-- The closed two-dimensional unit disk in the complex plane. -/
abbrev Disk := {z : ℂ // ‖z‖ ≤ 1}

/-- The inclusion of the unit circle into the closed disk. -/
def boundaryInclusion : C(Circle, Disk) where
  toFun z := ⟨z, le_of_eq (Circle.norm_coe z)⟩
  continuous_toFun := by fun_prop

/-- The actual topological disjoint union before attaching the disks. -/
abbrev Raw (X : Type u) (ι : Type v) := X ⊕ (Σ _ : ι, Disk)

variable {X : Type u} [TopologicalSpace X] {ι : Type v}

/-- Only boundary points are identified with their prescribed attaching images. -/
inductive AttachingRel (f : ι → C(Circle, X)) : Raw X ι → Raw X ι → Prop
  | boundary (i : ι) (z : Circle) :
      AttachingRel f (.inr ⟨i, boundaryInclusion z⟩) (.inl (f i z))

/-- The adjunction quotient, with its induced quotient topology. -/
def Space (f : ι → C(Circle, X)) := Quot (AttachingRel f)

instance (f : ι → C(Circle, X)) : TopologicalSpace (Space f) :=
  inferInstanceAs (TopologicalSpace (Quot (AttachingRel f)))

/-- The quotient map from the unglued topological disjoint union. -/
def quotientMap (f : ι → C(Circle, X)) : C(Raw X ι, Space f) :=
  ⟨Quot.mk _, continuous_quot_mk⟩

/-- The actual continuous inclusion of the original space. -/
def inclusion (f : ι → C(Circle, X)) : C(X, Space f) where
  toFun x := quotientMap f (.inl x)
  continuous_toFun := (quotientMap f).continuous.comp continuous_inl

/-- The characteristic map of an attached closed disk. -/
def characteristic (f : ι → C(Circle, X)) (i : ι) : C(Disk, Space f) where
  toFun z := quotientMap f (.inr ⟨i, z⟩)
  continuous_toFun := (quotientMap f).continuous.comp
    (continuous_inr.comp (continuous_sigmaMk (i := i)))

@[simp] theorem characteristic_boundary (f : ι → C(Circle, X)) (i : ι) (z : Circle) :
    characteristic f i (boundaryInclusion z) = inclusion f (f i z) :=
  Quot.sound (.boundary i z)

/-- The quotient map is a quotient map, not merely a continuous surjection. -/
theorem quotientMap_isQuotientMap (f : ι → C(Circle, X)) :
    Topology.IsQuotientMap (quotientMap f) := isQuotientMap_quot_mk

/-- Identify the boundary point of a disk with a circle point. -/
def diskBoundaryPoint (z : Disk) (h : ‖(z : ℂ)‖ = 1) : Circle :=
  ⟨z, mem_sphere_zero_iff_norm.mpr h⟩

/-- An algebraic invariant used only to distinguish points of the original space.
It is deliberately not asserted to be continuous. -/
def baseValue (f : ι → C(Circle, X)) : Raw X ι → Option X
  | .inl x => some x
  | .inr ⟨i, z⟩ => if h : ‖(z : ℂ)‖ = 1 then some (f i (diskBoundaryPoint z h)) else none

theorem baseValue_respects (f : ι → C(Circle, X)) {a b : Raw X ι}
    (h : AttachingRel f a b) : baseValue f a = baseValue f b := by
  cases h with
  | boundary i z =>
    change (if h : ‖(z : ℂ)‖ = 1 then some (f i (diskBoundaryPoint (boundaryInclusion z) h)) else none) = some (f i z)
    rw [dite_eq_left (Circle.norm_coe z)]
    rfl

/-- Algebraic readout of the base value descends through precisely the attaching relation. -/
def quotientBaseValue (f : ι → C(Circle, X)) : Space f → Option X :=
  Quot.lift (baseValue f) (fun _ _ h => baseValue_respects f h)

/-- The attaching quotient never identifies two distinct original points. -/
theorem inclusion_injective (f : ι → C(Circle, X)) : Function.Injective (inclusion f) := by
  intro x y h
  have h' := congrArg (quotientBaseValue f) h
  exact Option.some.inj h'

/-- The specified map on fundamental groups is induced by the actual inclusion. -/
def inclusionPi1 (f : ι → C(Circle, X)) (x₀ : X) :
    FundamentalGroup X x₀ →* FundamentalGroup (Space f) (inclusion f x₀) :=
  FundamentalGroup.map (inclusion f) x₀

end CellAttachment
