module

public import CellAttachment.Adjunction
public import CellAttachment.CircleGenerator
public import CellAttachment.GroupQuotient

@[expose] public section


/-!
# Exact target: attaching any family of two-cells

This module fixes the theorem statement before the geometric proof is assembled.
It contains definitions and no asserted or admitted cell-attachment theorem.
-/

noncomputable section
namespace CellAttachment
universe u v

variable {X : Type u} [TopologicalSpace X] {ι : Type v}

/-- The actual attaching loop in X, whiskered chronologically from the basepoint
along a chosen path, around the attaching circle once, and back. -/
def attachingLoop (f : ι → C(Circle, X)) (x₀ : X)
    (γ : ∀ i, Path x₀ (f i 1)) (i : ι) : Path x₀ x₀ :=
  (γ i).trans ((circleGenerator.map (f i).continuous).trans (γ i).symm)

/-- Its class in Mathlib's ordinary continuous-path fundamental group. -/
def attachingLoopClass (f : ι → C(Circle, X)) (x₀ : X)
    (γ : ∀ i, Path x₀ (f i 1)) : ι → FundamentalGroup X x₀ :=
  fun i => .mk (attachingLoop f x₀ γ i)

/-- Precisely the normal subgroup generated by the chosen conjugated attaching loops. -/
def attachingNormalClosure (f : ι → C(Circle, X)) (x₀ : X)
    (γ : ∀ i, Path x₀ (f i 1)) : Subgroup (FundamentalGroup X x₀) :=
  Subgroup.normalClosure (Set.range (attachingLoopClass f x₀ γ))

instance attachingNormalClosure_normal (f : ι → C(Circle, X)) (x₀ : X)
    (γ : ∀ i, Path x₀ (f i 1)) : (attachingNormalClosure f x₀ γ).Normal := by
  unfold attachingNormalClosure
  infer_instance

/-- The full arbitrary-family two-cell attachment theorem, including compatibility
of the quotient equivalence with the actual inclusion-induced map. The index
universe and the space universe are independent. -/
def completeStatement : Prop :=
  ∀ {X : Type u} [TopologicalSpace X] [PathConnectedSpace X] {ι : Type v}
    (f : ι → C(Circle, X)) (x₀ : X) (γ : ∀ i, Path x₀ (f i 1)),
    Function.Surjective (inclusionPi1 f x₀) ∧
    (inclusionPi1 f x₀).ker = attachingNormalClosure f x₀ γ ∧
    ∃ e : FundamentalGroup X x₀ ⧸ attachingNormalClosure f x₀ γ ≃*
      FundamentalGroup (Space f) (inclusion f x₀),
      e.toMonoidHom.comp (QuotientGroup.mk' (attachingNormalClosure f x₀ γ)) =
        inclusionPi1 f x₀

end CellAttachment
